### ISSUE TITLE
Practitioner : ID Nat PS n'a pas de system

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#100]
Bonjour
L'ID Nat PS dans practitioner n'a pas de system associé. En diffusion nous le diffusons donc en brut sans préciser ce que c'est .
Concretement il n'y a qu'un identifier dans practitioner donc peu de risque de confusion mais il pourrait être intéressant d'ajouter un type d'identifiant et un nos associé pour permettre au consommateur d'identifier clairement de quoi il s'agit.

**Comment by nriss** [comment]
Bien vu! Et ça n'est pas une ressource de l'Annuaire.

Pour l'instant, il faut utiliser ceci : urn:oid:1.2.250.1.71.4.2.1
cf : https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783648 https://esante.gouv.fr/sites/default/files/media_entity/documents/ci-sis_anx_sources-donnees-professionnels-structures_v1.5_0.pdf

On pourra réfléchir plus tard à l'usage d'un system de type uri, mais pour l'instant je ne sais pas dans quel IG on aura la ressource Practitioner, probablement fr-core
