### ISSUE TITLE
Slicing de alias dans Organization

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#101]
Bonjour
Nous ne comprenons pas comment véhiculer l'id de slicing dans l'attribut alias de organization.
Pour le moment, notre sortie est brute , comme par exemple : 
_"alias": [                "EHPAD GALIGNANI DENOMINATION",
"EHPAD GALIGNANI COMPLEMENT DENOMINATION",
"EHPAD GALIGNANI NOM OPE"  ]_

Cette sortie passe correctement le validate pour info, mais ne permet pas au consommateur de comprendre de quel alias on parle.
Quelle serait le résultat attendu pour notre exemple ?

**Comment by nriss** [comment]
Ca devrait être sur l'ID : https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-organization.html
cf https://www.hl7.org/fhir/R4/datatypes.html#representations

La proposition de @mathieu-decarvalho est peut être préférable https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/103
