### ISSUE TITLE
Notion en trop dans ROROrganization

### ISSUE THREAD

**Issue by mathieu-decarvalho** [ansforge/IG-fhir-repertoire-offre-ressources-sante#102]
Resource Profile: ROROrganization

A quoi correspond cette notion qui ne doit pas être présente içi?

[type:fonctionLieu](https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-organization-definitions.html#Organization.type:fonctionLieu)

**Comment by paulineheurtebise** [comment]
Effectivement je pense que c'est une coquille dans la ressource après vérification. 
Impacts : 
- ME -> ok pas d'impact
- Le mapping ne contient pas cet élément -> ok pas d'impact 
- Ressource -> à corriger, je le fais
