### ISSUE TITLE
Mauvais Mapping ROROrganization

### ISSUE THREAD

**Issue by mathieu-decarvalho** [ansforge/IG-fhir-repertoire-offre-ressources-sante#103]
Pour ROROrganization, le mapping des noms dans ALIAS est mauvais.

Les 6 notions suivantes sont dans des champs distincts en FHIR :

- Name pour la Raison social de l'EJ
- ror-organization-additional-name pour le nom complémentaire de l'EJ
- alias:OIName pour le nom de l'OI
- alias:denomination pour le nom de l'EG
- alias:additionalDenomination pour le nom complémentaire de l'EG
- alias:operationalName pour le nom opérationnel EG

or la modélisation ne correspond pas du tout à cela.

Nous avons besoin de 3 notions pour les organisations peu importe leur type, EJ, EG, ...

Il faut un nom principal (name), un nom complémentaire (extension ou alias) et un nom opérationnel (extension ou alias).

Pour moi il faut donc:
- name avec : Raison social de l'EJ ou nom de l'EG ou nom de l'OI
- ror-organization-additional-name avec : nom complémentaire de l'EJ ou nom complémentaire de l'EG
- alias avec : le nom opérationnel EG

**Comment by nriss** [comment]
Ca simplifie la modélisation, j'aime ça ! :)

**Comment by paulineheurtebise** [comment]
Effectivement, je pense que c'est une erreur lors de la création de la SD. 
J'ai retrouvé les premiers mapping qui sont conformes à la proposition de Mathieu. 

Les impacts sont donc :  

- [ ] - ME => pas d'impact ok
- [ ] - Mapping => A mettre en cohérence avec les modifications
- [ ] - Corriger la ressource => A modifier 
- [ ] - Narratif / Requete exemple => A vérifier 

@PhilippeC-ANS  est ce que c'est bien ok pour toi cette proposition de modification ?

**Comment by paulineheurtebise** [comment]
Merci Philippe ! Normalement j'ai retrouvé les attributs dans le modèle d'expo, merci.
