### ISSUE TITLE
Implementation Guide - Exemple de réponse FHIR sur le search

### ISSUE THREAD

**Issue by Omezhoud** [ansforge/IG-fhir-repertoire-offre-ressources-sante#104]
Bonjour, 

Pour l'IDF , nous devons migrer nos services régionaux vers les service FHIR du ROR N. Pour nous aider à la conception nous avons besoin d'exemple de réponse FHIR au search.

Nous recherchons de la disponibilité en lit ( location ) avec en réponse le Healthcarservice  et les organization parentes

Pouvons-vous ajouter dans l'implémentation guide , le bundle FHIR  de la réponse ?
Location-> healthcareService : UE/facility=> Organization  : de l'UF à l'EG/EJ

Par avance merci

Oualid Mezhoud  (SESAN IDF)

**Comment by sdemeyANS** [comment]
Bonjour,
Pour information une issue similaire existe : #80

**Comment by sdemeyANS** [comment]
voir issue #80
