### ISSUE TITLE
Implementation guide - Question Structure définition du HealthcareService

### ISSUE THREAD

**Issue by Omezhoud** [ansforge/IG-fhir-repertoire-offre-ressources-sante#105]
Bonjour , 

Dans l'implémentation guide , sur la structure définition du HealthcareService , la référence/lien à l'Organization parente n'est pas présente

10.1.2 StructureDefinition-ror-healthcareservice

**Comment by paulineheurtebise** [comment]
Dans le profil RORHealthcarService, la référence à l'organization se fait via l'attribut providedBy qui est natif dans FHIR. 
Vous devriez le voir dans le profil : https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-healthcareservice.html

**Comment by sdemeyANS** [comment]
Bonjour @Omezhoud 
Nous fermons cette issue.
N'hésitez pas à la rouvrir si besoin.
