### ISSUE TITLE
Implementation guide - Question Structure définition de l'Organization

### ISSUE THREAD

**Issue by Omezhoud** [ansforge/IG-fhir-repertoire-offre-ressources-sante#106]
Bonjour ,

Dans l'implémentation guide , sur la structure définition de l' Organization,  la référence/lien entre les organization n'est pas présente .

10.1.3 StructureDefinition-ror-organization

**Comment by sdemeyANS** [comment]
Bonjour,
Est-ce cet élément que vous recherchez ? https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-organization-definitions.html#diff_Organization.partOf

**Comment by sdemeyANS** [comment]
Bonjour @Omezhoud est-ce que cela répond à votre question ? Pouvons nous clore cet issue?

**Comment by sdemeyANS** [comment]
Bonjour @Omezhoud,
Nous fermons cette issue. N'hésitez pas à la rouvrir si besoin
