### ISSUE TITLE
Implementation guide - Question Structure définition de l'organization - type d'organisation

### ISSUE THREAD

**Issue by Omezhoud** [ansforge/IG-fhir-repertoire-offre-ressources-sante#107]
Bonjour, 

Dans la structure définition de la ressource organization , le type d'organisation n'est pas présent . est-ce qu'il est implémenté ? 

Nous en avons besoin pour identifier l'EG parmi les organisation d'un healthcareService.

**Comment by PhilippeC-ANS** [comment]
De mon point de vue : 
- Déjà réalisé : 
Le mapping de la ressource organization contient déjà un firepath "OrganizationType" lié au JDV J203 (https://mos.esante.gouv.fr/NOS/JDV_J203-TypeOrganisationInterne-ROR/) et qui doit permettre de véhiculer le typeOI.

- évoqué mais non réalisé : 
Compléter ce JDV pour permettre de véhiculer également les types EG et EJ.
Même si cela est envisageable, je ne trouve pas que ce soit une bonne idée de demander à nos consommateurs d'interpréter les identifiants pour déterminer s'il s'agit d'une EJ, d'un EG ou d'une OI.

Cette information pourrait provenir de la TRE R67 (https://mos.esante.gouv.fr/NOS/TRE_R67-TypeStructure-EJ-EG/TRE_R67-TypeStructure-EJ-EG.pdf) et enrichir le J203 => D'un point de vue NOS il me semble que ça ne devrait pas représenter une difficulté (à valider avec l'équipe NOS).
_(nota : le libellé associé au JDV ne serait plus tout à fait exact, mais cela ne me semble pas être un vrai problème)_

Je laisse l'équipe technique se positionner sur l'implémentation de l'organizationType dans le ROR national.

**Comment by Omezhoud** [comment]
Bonjour , 

@paulineheurtebise , à priori non, pour le Finess c'est le même code, le type d'identifiant ne permettra donc pas d'identifier l'EG de l'EJ . 

Si on peut enrichir la TRE , et véhiculer le type avec les EJ/EG , ça résoudrait  notre problème.

**Comment by paulineheurtebise** [comment]
Atelier 06/09 : 
o	DM NOS par Philippe pour compléter le JDV. 
o	Issue clôturée après la prise en compte de la DM

**Comment by sdemeyANS** [comment]
la génération des fichiers NOS de septembre a eu lieu
Création des catégories organization EJ et EG effectuée

**Comment by PhilippeC-ANS** [comment]
@sdemeyANS  Doit-on fermer ce ticket maintenant ou lorsque les développements RORN auront été réalisés afin d'exposer cette information des types EJ et EG ?

**Comment by sdemeyANS** [comment]
> @sdemeyANS Doit-on fermer ce ticket maintenant ou lorsque les développements RORN auront été réalisés afin d'exposer cette information des types EJ et EG ?

Le repo github concerne l'Implementation Guide donc je pense que l'issue peut être close sur github

**Comment by Omezhoud** [comment]
Bonjour PhilippeC-ANS, 

Quand est prévu l'implémentation, ? Est-ce que tu pourras nous informer dès que l'évolution est déployée , à minima en recette ?
