### ISSUE TITLE
Evolution search- Ressource Healthcareservice - Ajout d'un critère type de  fermeture 

### ISSUE THREAD

**Issue by Omezhoud** [ansforge/IG-fhir-repertoire-offre-ressources-sante#108]
Bonjour, 

Dans le search , le ROR N renvoie toute les unités/healthcareservice  ouvertes et fermées sans distinction.

Pour nos usages régionaux nous avons besoin lors de la recherche , notamment de disponibilité en lits, de ne ne récupérer que les unités /Healthcareservice "ouvertes"

Nous avons donc besoin d'un critrère de recherche sur le type de fermeture sur la ressource healthcareservice . Il nous permettra également de distinguer les unités fermés définitivement de celle temporairement ( ex: période d'été ...) , ce dernier étant utiles pour d'autres usages.

Par avance merci.

Oualid  Mezhoud

**Comment by sdemeyANS** [comment]
Bonjour,
Nous allons analyser votre demande d'évolution et vos faire un retour ASAP.

**Comment by PhilippeC-ANS** [comment]
D'un point de vue métier, ce critère de recherche a du sens et des usages immédiats.
Il faut pouvoir faire une recherche sur ce champ selon la valeur saisie, mais également sur l'absence de valeur (ouverte = n'ayant aucune information en type de fermeture)

**Comment by paulineheurtebise** [comment]
Atelier 06/09 : 
o	Evolution à discuter 
o	Philippe analyse le besoin fonctionnel et répond à l’issue (fait)
o	Si prise en compte déterminer où s’inscit l’évolution dans la roadmap.

**Comment by sdemeyANS** [comment]
Bonjour,
Je pense que cela a été traité dans la PR https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/336
La modification a donc été intégrée dans le main.
N'hésitez pas à commenter/ouvrir de nouveau l'issue si le traitement ne correspond pas à votre attente

**Comment by sdemeyANS** [comment]
suppression du commentaire précédent et réouverture de l'issue (confusion d'issue) désolé

**Comment by sdemeyANS** [comment]
Le critère de recherche a utilisé pour le type de fermeture est characteristic https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-add-sp-sur-healthcareservice/ig/search_param.html#structuredefinition-ror-healthcareservice
La précision a été ajoutée: https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/search_param.html#structuredefinition-ror-healthcareservice suite à la PR #343
