### ISSUE TITLE
Evolution search- Ressource Healthcareservice - Ajout d'un critère "Date de fermeture "

### ISSUE THREAD

**Issue by Omezhoud** [ansforge/IG-fhir-repertoire-offre-ressources-sante#109]
Bonjour,

Dans le search , le ROR N renvoie toute les unités/healthcareservice ouvertes et fermées sans distinction.

Pour nos usages régionaux nous avons besoin lors de la recherche , notamment de disponibilité en lits, de ne ne récupérer que les unités /Healthcareservice "ouvertes"

Nous avons donc besoin d'un critère/paramètre de recherche sur la **date de fermeture** dans la ressource healthcareservice . 

Par avance merci.

Oualid Mezhoud

**Comment by sdemeyANS** [comment]
Bonjour,
Nous allons analyser votre demande d'évolution et vos faire un retour ASAP.

**Comment by PhilippeC-ANS** [comment]
@Omezhoud 
Salut Oualid,
je ne vois pas de cas métier nécessitant une recherche sur cette date (sous réserve que l'on dispose du critère sur le type de fermeture tracé dans le ticket 108).
Peux-tu m'éclairer sur les cas métier où cette date serait utilisée ?

Merci
Philippe

**Comment by paulineheurtebise** [comment]
Atelier 06/09 : 
o	Evolution à discuter 
o	Philippe analyse le besoin fonctionnel et répond à l’issue (fait)
o	Si prise en compte déterminer où s’inscit l’évolution dans la roadmap.

**Comment by jcserafini** [comment]
J'ai l'impression qu'il reste une question ouverte pour @Omezhoud non ?

**Comment by sdemeyANS** [comment]
Bonjour
Nous avons ajouté un nouveau search param https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/SearchParameter-ror-sp-healthcareservice-notavailable-closing-reopeningdate.html.
Il est intégré dans la version ci-build du guide et sera donc disponible dans la prochaine version du guide d'implémentation.
