### ISSUE TITLE
ROR N recette - search FHIR - requête en exemple sur IG KO

### ISSUE THREAD

**Issue by Omezhoud** [ansforge/IG-fhir-repertoire-offre-ressources-sante#110]
Bonjour , 

Sur le ROR N de recette ,avec Postman j'appelle le search fhir , en utilisant une requête en exemple sur l'IG . Mais une erreur est retournée indiquant que les paramètres de recherche ne sont pas connus

6.1.6.1 : Scénario 1 : Recherche sur un critère capacitaire #1

https://api.rortest.esante.gouv.fr/ws-diffusion-fhir-auth//HealthcareService?speciality=https://mos.esante.gouv.fr/NOS/TRE_R211-ActiviteOperationnelle/FHIR/TRE-R211-ActiviteOperationnelle|356&location.capacity-status=https://mos.esante.gouv.fr/NOS/TRE_R330-StatutCapacite/FHIR/TRE-R330-StatutCapacite|02&location.nb-capacity=gt0&_revinclude=Location:healthcareservice

Erreur retournée : 
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "not-supported",
            "diagnostics": "Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[HealthcareService] with parameters [[speciality, _revinclude, location.capacity-status, location.nb-capacity]]"
        }
    ]
}

**Comment by nriss** [comment]
Hello, 
Cette question n'est pas en lien avec l'IG mais plutôt au niveau de l'implem à priori :)

**Comment by Omezhoud** [comment]
Salut , 

Est-ce que je dois remonter le problème sur un autre canal ?

**Comment by sdemeyANS** [comment]
> Salut ,
> 
> Est-ce que je dois remonter le problème sur un autre canal ?

Hello

J'ai transmis à Romain

**Comment by sdemeyANS** [comment]
Suite échange avec Romain, il y a effectivement une typo déjà dans la requête speciality au lieu de specialty

**Comment by nriss** [comment]
> Suite échange avec Romain, il y a effectivement une typo déjà dans la requête speciality au lieu de specialty

De plus, le searchparam _revinclude=Location:healthcareservice n'existe pas. Je pense qu'il faut le remplacer par _include=HealthcareService:location (vérifier avec Romain si l'attribut location est bien populé)

**Comment by sdemeyANS** [comment]
pour information le résultat de la correction est visible en preview ici https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/ . En attendant que le correctif de cet issue soit embarqué dans une prochaine release de l'implementation et quelle soit publiée ici https://interop.esante.gouv.fr/ig/fhir/ror/
