### ISSUE TITLE
Where manquant à ...(url)

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-repertoire-offre-ressources-sante#115]
https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/d830410f043ed5b3afe7efa006b9f036ef7486c0/input/fsh/instances/ror-sp-gender-capacity-available.fsh#L10

**Comment by sly-kereval** [comment]
En effet, il manquait bien un where.

Une fois cette erreur corrigée, une autre erreur est remontée dans le rapport de validation. 
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/125375447/bc878747-dacc-4861-a3c3-84e798809d24)

En remplaçant `valueCode` par `value`, il n'y a plus d'erreur. Est-ce que vous validez cette syntaxe ? Si c'est ok, je corrigerai les autres SP qui contiennent des erreurs.

**Comment by nriss** [comment]
On a fait comme us-core, je ne comprends pas : 
http://hl7.org/fhir/us/core/STU5/SearchParameter-us-core-condition-asserted-date.html

Peux-tu tester [...].value.as(code) comme indiqué ici : https://smilecdr.com/docs/fhir_standard/fhirpath_expressions.html ?

**Comment by sly-kereval** [comment]
Je ne comprends pas, depuis ce matin, plus aucune erreur sur les search parameters, même sur la branche main (donc sans aucune correction) : https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/actions/runs/6035120519

**Comment by nriss** [comment]
Très probablement issu de nouvelles releases ! https://github.com/hapifhir/org.hl7.fhir.core/releases
Ca devait être un bug du validateur, pour moi l'expression était bonne

Tant mieux, on laisse comme ça du coup :) J'espère que tu n'as pas trop entamé les travaux

**Comment by sdemeyANS** [comment]
j'étais en train de regarder les releases du validator justement:
On télécharge à chaque fois la dernière
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/5e8e5e56-0b03-4bec-bb66-b770a03d6b57)

et il y a eu une nouvelle version il y a 17 h 
https://github.com/hapifhir/org.hl7.fhir.core/releases/

**Comment by sly-kereval** [comment]
Je peux donc fermer l'issue et supprimer la branche ?

**Comment by sly-kereval** [comment]
Actuellement sans aucune correction il n'y a plus d'erreur concernant les urls dans le rapport de validation.

**Comment by sdemeyANS** [comment]
@sly-kereval tu peux nous pointer le rapport de validation sans erreurs stp ?

**Comment by sly-kereval** [comment]
Voilà : https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/actions/runs/6035120519

**Comment by nriss** [comment]
L'erreur est toujours présente ici : https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/actions/runs/6047735010 (workflow lancé il y a 4h)
