### ISSUE TITLE
ROR N RECETTE - search- nombre total de résultat incohérent 

### ISSUE THREAD

**Issue by Omezhoud** [ansforge/IG-fhir-repertoire-offre-ressources-sante#118]
Bonjour, 

Sur le ROR N de recette j'ai fait un search "simple" pour récupérer toutes les locations

https://api.rortest.esante.gouv.fr/ws-diffusion-fhir-auth/Location

Dans la réponse j'ai un total de 79320 , alors que la réponse ne comporte que quelques centaines de location

    "resourceType": "Bundle",
    "id": "032af1aa-9236-429a-8478-383b70b9138d",
    "meta": {
        "lastUpdated": "2023-08-31T09:16:14.689+00:00"
    },
    "type": "searchset",
    "total": 79320,

**Comment by nriss** [comment]
Bonjour, les résultats sont paginés, il y a à priori des liens vers les prochains résultats : current, previous, et next au sein du bundle (cf Bundle.link : https://www.hl7.org/fhir/R4/bundle.html)

Si bien implémenté, le paramètre de recherche _count permet de définir le nombre de résultats par recherche : https://www.hl7.org/fhir/R4/search.html#count

**Comment by Omezhoud** [comment]
Bonjour ,

Autant pour moi, je n'avais pas vu la relation next  ( pourtant au début...)

Ok donc par défaut c'est 200 . 

Je viens de tester le count. Je comprends mieux .

Le ticket peut être fermé.
