### ISSUE TITLE
ROR N RECETTE- search- erreur renvoyé sur la ressource Organization

### ISSUE THREAD

**Issue by Omezhoud** [ansforge/IG-fhir-repertoire-offre-ressources-sante#119]
Bonjour, 

Sur le ROR N de recette , je veux récupérer toute les organization mais une erreur est renvoyée

https://api.rortest.esante.gouv.fr/ws-diffusion-fhir-auth/Organization

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Page size must not be less than one!"
        }
    ]
}

**Comment by loic-brtd** [comment]
Bonjour,

Ce bug a été identifié aussi de notre côté, nous travaillons sur sa correction.
Ticket Jira (accessible par l'équipe ROR national) : https://jira.fsc.atos-services.net/browse/FMAR-1314.

Cordialement,
Loïc BERTRAND
ROR National

**Comment by jcserafini** [comment]
bug corrigé @Omezhoud
