### ISSUE TITLE
[narratif] spécifier correspondance specs et version solution ROR

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-repertoire-offre-ressources-sante#129]
Afin de clarifier ce qui a été implémenté dans la solution ROR à date par rapport aux specs, ajouter "disponible à partir de ROR 2.x" au niveau des cas d'usage et remettre al correspondance specs current et solution ROR de l'history sur la page d'accueil

**Comment by sdemeyANS** [comment]
@jcserafini pour info preview sur la nouvelle branche https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-add-version-ROR-N/index.html

**Comment by sdemeyANS** [comment]
@jcserafini est-ce que les search param tagué "*Critères de recherche qui seront applicables ultérieurement" dans https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/search_param.html le sont toujours dans la solution ROR 2.3 ?

**Comment by sdemeyANS** [comment]
je mets en 0.2.0 pour tenter d'insérer ces changements pour la prochaine publi. Si c'est bloquant je le remettrai en tbd

**Comment by nriss** [comment]
Totalement d'accord @sdemeyANS ! Ca va faciliter la lecture des consommateurs et éviter les erreurs

**Comment by jcserafini** [comment]
@sdemeyANS  OK pour moi

**Comment by sdemeyANS** [comment]
comme validé ce jour en réunion on enlève les tableaux dans specs techniques et on reférences les pages serach_param et modifiers
