### ISSUE TITLE
Question syntaxe include iterate

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#130]
Nous constatons que dans notre développement ROR N , la syntaxe pour récupérer les organizations parents qui a été implémentée est la suivante : 
HealthcareService?**_include=HealthcareService:providedBy&_include:iterate=Organization:partOf**

La syntaxe présente dans l'IG est la suivante : 
HealthcareService?**_include:iterate=HealthcareService:organization**

Même si nous envisageons de nous réaligner sur l'IG, la syntaxe développée est elle correcte ? Peut on la conserver ?

**Comment by paulineheurtebise** [comment]
Merci Jean- Claude d'avoir relevé l'incohérence. 

A mon sens, la syntaxe correcte est la suivante : 
HealthcareService?_include=HealthcareService:organization&_include:iterate=Organization:partof

La spécification est plus détaillé en R5 : http://hl7.org/fhir/search.html#modifieriterate
En complément nous avons trouvé les slides des [FHIR dev days 2020](https://www.devdays.com/wp-content/uploads/2020/12/vcfzh_20201119_ReneSpronk_AdvancedSearch.pdf). 

L'exemple qui correspond à notre cas est : 
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/122790741/dbae1c21-267e-4a21-bf3f-026b2186e985)

Je créé une branche pour corriger de suite.

**Comment by jcserafini** [comment]
@paulineheurtebise @sdemeyANS Je réouvre ce ticket et je reformule ma question pour être sur de bien comprendre.

Je comprend que la syntaxe qui était dans l'IG est incorrecte et que vous allez la corriger OK.

Ma question portait sur la syntaxe initialement indiquée et qui est celle qu'on a développée : 
HealthcareService?_include=HealthcareService:providedBy&_include:iterate=Organization:partOf

Est elle syntaxiquement incorrecte ? J'insiste un peu désolé mais comme l'attribut entre HS et orga est providedBy, j'avais l'impression que c'était utilisable.

**Comment by paulineheurtebise** [comment]
Hello, 
Oui la syntaxe "HealthcareService?_include=HealthcareService:providedBy&_include:iterate=Organization:partOf" est incorrecte. 
providedBy c'est le nom de l'attribut pas celui du critère de recherche qui organization.

**Comment by jcserafini** [comment]
Hello et merci Pauline,
Nous prenons en compte cette modification, je me permets de fermer ce ticket  !
