### ISSUE TITLE
Pourquoi est-ce qu'il s'agit d'une extension et pas d'une ressource Device ?

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-repertoire-offre-ressources-sante#131]
https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/b57f184ed889cf4bde3f8e066a4fa05d5778b43f/input/fsh/profiles/RORLocation.fsh#L100C5-L100C25

**Comment by sdemeyANS** [comment]
Décision suite à réunion de mapping FHIR du 1er et 2 juin 2022
Device ne correspond pas à la Définition Equipement dans le ROR @PhilippeC-ANS tu confirmes ?

**Comment by PhilippeC-ANS** [comment]
Je confirme.
La question s'était posée, mais la ressource Device n'avait pas été retenue : elle permet d'identifier unitairement et très finement des équipements (dont modèle, numéro de série, ...) ce qui n'est pas l'esprit des "équipements spécifiques" dans le ROR. C'est un concept bcp plus macro que l'on associe à une quantité et Device ne semblait pas adapté.

**Comment by sdemeyANS** [comment]
A voir si on ajoute cette explication dans l'IG
