### ISSUE TITLE
Liens entre ressources FHIR

### ISSUE THREAD

**Issue by isidacally** [ansforge/IG-fhir-repertoire-offre-ressources-sante#136]
Bonjour,

Est-ce que ce schéma entre les ressources FHIR est vlide ?
![Modelisation_ressources_FHIR](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/139139121/9edad9b2-c43f-4f31-beba-1614d1295fd2)

Merci d'avance.

Cordialement,

**Comment by paulineheurtebise** [comment]
Les flèches qui arrivent dans HealthcareService ne sont pas dans le bon sens. 
C'est HSC qui fait référence à Organization et Location.

**Comment by isidacally** [comment]
Diagramme mis à jour.
Merci.
