### ISSUE TITLE
Incohérence syntaxe recherche dans l'IG

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#137]
Les développeurs ont détecté une incohérence dans l’Implementation Guide (IG) FHIR sur la syntaxe de recherche avec chaînage des critères sur d’autres ressources (exemple : recherche de HealthcareService sur des critères de Location).
 
Dans la plupart des exemples décrits jusqu’ici dans l’IG, on voit la syntaxe suivante, avec deux points « : » :
get[BASE]/HealthcareService?location:intervention-zone=XXX
https://interop.esante.gouv.fr/ig/fhir/ror/0.1.0/specifications_techniques_3.html -> scénario 6 par exemple

Pour autant, l’IG indique une syntaxe avec un point « . » sur la même page en section 5.1.4:
"Pour cela utiliser la syntaxe suivante : location.[NOM CRITERE]"

Dans la page de l’IG concernant la « Recherche d'offre avec données capacitaires », on trouve aussi un mix des deux, avec une majorité de « . » -> https://interop.esante.gouv.fr/ig/fhir/ror/0.1.0/specifications_techniques_4.html
&location.capacity-closing-type
&location.capacity-status
&location:equipment-type

Dans le ROR national, comme nous nous sommes basés sur les premiers exemples de l’IG nous avons mis deux points « : » systématiquement.

**Comment by sdemeyANS** [comment]
corrigé ici https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/79 mais pas encore publié ?

**Comment by sdemeyANS** [comment]
voir https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_3.html
