### ISSUE TITLE
Utilisation des search parameters en ligne ou unique

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#143]
# Description du problème
Sur tous les search parameters on a la mention : 
Multiples | The parameter cannot repeat or have multiple values

On se demande si c'est vraiment pertinent : sur certains critères n'est ce pas utile de permettre de mettre plusieurs critères ? (rechercher une offre proposant une liste d'équipements, une liste de zones d'interventions etc.

# Fichier•s concerné•s
Vu dans l'IG

# Solution proposée
Indiquer pour chaque SP si on peut mettre une liste ou une valeur unique

**Comment by nriss** [comment]
Le multipleOr / multipleAnd n'est pas précisé dans les SP du ROR. Ce message est affiché automatiquement par l'IG publisher.

En R5, c'est au choix du serveur:
- https://www.hl7.org/fhir/searchparameter-definitions.html#SearchParameter.multipleOr

**Comment by sdemeyANS** [comment]
Bonjour,
Et il est écrit en R5 que "par défaut, c'est au choix du serveur"
<img width="312" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/2cbfb2ef-090c-4dd5-8410-9838ab18d372">

Si on prend par exemple 
[ANS.FHIR.FR.ROR\ror-sp-additional-bed-type - FHIR v4.0.1 (esante.gouv.fr)](https://interop.esante.gouv.fr/ig/fhir/ror/SearchParameter-ror-sp-additional-bed-type.html)
<img width="740" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/0884744a-9322-4e18-b0d1-4a7fe7258df7">

la ligne Multiples est générée par défaut il me semble  vu que c'est en anglais

donc selon le besoin il faudra effectivement décier si on l'ajoute à tous ou on voit pour chaque critère

**Comment by sdemeyANS** [comment]
@jcserafini on attend donc vos directives :)

**Comment by jcserafini** [comment]
@sdemeyANS j'ai analysé et j'ai la liste de ce qu'on a développé en multi vs mono. Cependant, les dévs m'ont indiqué qu'ils ont essayé de permettre la recherche multi à partir du _filter.

Vu avec @PhilippeC-ANS , tant qu'on peut faire du multi, peu importe que ce soit avec ou sans le filter. 
On aimerait cependant être cohérents , permettre ou ne pas permettre le multi sans filter de la même manière pour tous les critères (ce qui n'est pas le cas aujourdhui). Vous avez une préconisation ? On peut en parler lundi

**Comment by sdemeyANS** [comment]
A noté avec la nouvelle version de l'IG Publisher : 
<img width="830" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/3bf8d14c-0636-41f8-9958-dad5c78bec43">

**Comment by jcserafini** [comment]
@sdemeyANS on implémente le multiple dans la prochaine version. Ca fonctionnera en OR
