### ISSUE TITLE
verification mapping adresse EG 

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-repertoire-offre-ressources-sante#149]
# Description du problème
Suite issue [Souci modélisation EG - géolocalisation · Issue #94 · ansforge/IG-fhir-repertoire-offre-ressources-sante (github.com)](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/94)
vérifier le mapping
suite retour @LudivineLacour 
"as de lien entre Organization et Location alors que dans le mapping il était inscrit que les éléments d'adresse de l'EG sont diffusés dans la ressource Location. Jean-Claude m'a indiqué que finalement les éléments d'adresse de l'EG seraient diffusés dans Organisation comme pour les EJ et que des extensions seraient ajoutées pour les points de géolocalisation utiles aux EG"

# Fichier•s concerné•s
xls mapping

# Solution proposée
vérifier et corriger le mapping le cas échéant

**Comment by sdemeyANS** [comment]
@paulineheurtebise A noter un autre sujet mapping dans l'issue #151

**Comment by paulineheurtebise** [comment]
sujets traités dans la maj du mapping : 
#86 Adresse streetNameHamlet en precinct
#69 RORCalculatedDistance dans HSC
#94 et #149 Ajout managingOrganization dans Location
#151 Ajout Location.status
#68 HSC Contact

**Comment by sdemeyANS** [comment]
@LudivineLacour traitement en cours dans https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/154
OK pour toi?
