### ISSUE TITLE
Incohérence critère de recherche Location?status

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#151]
# Description du problème
 
Atos a repéré une potentielle incohérence sur le critère de recherche /Location?status=… (et /HealthcareService?location.status=…).
 
Dans la spec FHIR, ce critère porte sur le champ « Location.status »  (https://hl7.org/fhir/R4/location.html#search) 

Le tableau des critères de l’IG semble indiquer la même chose (https://interop.esante.gouv.fr/ig/fhir/ror/search_param.html) :

Cependant, le champ « Location.status » n’apparaît pas dans le mapping de l’IG (https://interop.esante.gouv.fr/ig/fhir/ror/mapping.html). Dans le ROR, on diffuse toujours ce champ avec la valeur « active ».
Le champ qui s’en rapproche le plus est l’extension RORLocationStatus (https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-location-status.html)
 
En résumé :
•	Si le critère « status » porte sur le champ « Location.status », ne faudrait-il pas que ce champ apparaisse dans le mapping ? (avec un mapping explicite vers les valeurs possibles en FHIR « active | suspended | inactive »)
•	Si le critère « status » porte sur l’extension « RORLocationStatus », ce n’est pas cohérent avec la sémantique de ce critère dans spec FHIR (https://hl7.org/fhir/R4/location.html#search)

# Fichier•s concerné•s

# Solution proposée

**Comment by sdemeyANS** [comment]
Bonjour @jcserafini 
traitement en cours ici https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/154 
Est-ce OK pour toi ?

**Comment by paulineheurtebise** [comment]
Je complète l'issue à postériori pour donner du détail sur les actions réalisées, n'hésitez pas à revenir dessus si besoin. 
J'ai ajouté l'attribut (natif) status car il n'était pas présent et le binding required avec le VS FHIR [location-status](http://hl7.org/fhir/valueset-location-status.html). 
Le paramètre de recherche (natif) status correspond bien à cet attribut. 
Nous n'avons pas de paramètre de recherche sur l'extension [ror-location-status](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-location-definitions.html#Location.extension:ror-location-status)

**Comment by sdemeyANS** [comment]
> Il aurait été préférable de mettre cette extension au niveau de Location.status, les clients risquent de nous le reprocher.. Mais peut être trop pénible pour changer aujourd'hui ?

Cela dépend du besoin ?
Si changement nécessaire il devra intégrer un nouveau cycle catr il faut voir l'impact dev

**Comment by nriss** [comment]
Ca me paraît plus standard de mettre cette extension au niveau du status

**Comment by sdemeyANS** [comment]
> Ca me paraît plus standard de mettre cette extension au niveau du status

Je propose que nous fassions une nouvelle issue dans ce cas.
Avec besoin d'analyse d'impact côté pour le changement
