### ISSUE TITLE
Question sur les limites des APIs

### ISSUE THREAD

**Issue by JulienDelamotteKeyrus** [ansforge/IG-fhir-repertoire-offre-ressources-sante#152]
Bonjour nous avons différentes questions sur les limites des APIs mise en place : 

1) Est-il possible de faire un appel asynchrone ? (comme documenté ici : https://build.fhir.org/async.html)
2) Quelle est la fréquence d'appel maximales sur les différentes APIs ? Quelle est la conséquence d'un dépassement de cette fréquence ?

Merci,

Cordialement

**Comment by sdemeyANS** [comment]
Bonjour,
Concernant le point 1 des travaux sont en cours cf issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/95
Bien cordialement,

**Comment by jcserafini** [comment]
@sdemeyANS @JulienDelamotteKeyrus Pour clarifier : mise à part la méthode export nous n'avons pas prévu de permettre au consommateur d'avoir un mode asynchrone sur les appels.
En gros : on pourra consommer l'ensemble de l'offre de santé qu'on aura pré généré le matin, mais on ne pourra pas demander au ROR N de préparer une réponse asynchrone à une requête spécifique d'un consommateur

**Comment by jcserafini** [comment]
@JulienDelamotteKeyrus AI je répondu à votre question ?

**Comment by sdemeyANS** [comment]
Bonjour,
Je clos cette issue.
N'hésitez pas à la rouvrir si besoin.
Bien cordialement
