### ISSUE TITLE
CapabilityStatement - searchInclude et searchRevInclude

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-repertoire-offre-ressources-sante#162]
# Description du problème
En lisant les capability statement j'ai remarqué que nous n'avions pas mis les parties searchInclude et searchRevInclude alors que c'est utilisé. Il faut les ajouter non ? 

# Fichier•s concerné•s
[ror-consommateur](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/instances/ror-consommateur.fsh)
[ror-serveur](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/instances/ror-serveur.fsh)

# Solution proposée

**Comment by sdemeyANS** [comment]
oui une review complete des capability statement est nécessaire
