### ISSUE TITLE
[Recette]Recherche Offres + capacités : Réponse toujours vide du ROR national

### ISSUE THREAD

**Issue by isidacally** [ansforge/IG-fhir-repertoire-offre-ressources-sante#164]
# Description du problème
Bonjour,

Le ROR national retourne toujours un résultat à 0 lors d'une recherche d'offres + capacités.

# Fichier•s concerné•s
[req_FHIR_AO_175_08112023.txt](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/files/13298640/req_FHIR_AO_175_08112023.txt)

# Solution proposée

**Comment by jcserafini** [comment]
@isidacally Je pense que l'erreur vient du system du critère capacity status. 
Vous avez mis : https://mos.esante.gouv.fr/NOS/TRE_R330-**StatutCapacite**/FHIR/TRE-R330-**StatutCapacite**
Le system de cette nos est : https://mos.esante.gouv.fr/NOS/TRE_R330-**TypeStatutCapacite**/FHIR/TRE-R330-**TypeStatutCapacite**


@sdemeyANS Le souci est présent dans un exemple ici : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_4.html 
je pense qu'il faudrait corriger l'exemple

**Comment by sdemeyANS** [comment]
> @sdemeyANS Le souci est présent dans un exemple ici : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_4.html je pense qu'il faudrait corriger l'exemple
OK on regarde cela

**Comment by isidacally** [comment]
Bonjour,  merci pour votre retour en effet ça fonctionne mieux avec la bonne URL.
