### ISSUE TITLE
IG : incohérence sur le paramètre include dans la requête de recherche offres + capacités - scénario-1

### ISSUE THREAD

**Issue by isidacally** [ansforge/IG-fhir-repertoire-offre-ressources-sante#166]
# Description du problème
Au niveau de l'Implémentation Guide dans la section : 
"Spécifications techniques >> Recherche d'offre avec données capacitaires" nous avons une incohérence sur le paramètre include pour le scénario-1.

# Fichier•s concerné•s

![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/139139121/6291b945-3341-4bac-abd4-317b935856cf)

# Solution proposée

**Comment by sdemeyANS** [comment]
Bonjour,
Effectivement.
Merci pour ce retour.
Nous regardons et corrigeons rapidement
Bien cordialement,

**Comment by sly-kereval** [comment]
Bonjour, 

Cette erreur a déjà été corrigée en vue de la prochaine release, en attendant la preview est disponible ici : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_4.html. 

Merci pour ce retour.

**Comment by paulineheurtebise** [comment]
Je ferme l'issue car corrigé. A ré-ouvrir si besoin.
