### ISSUE TITLE
IG : Référence NOS manquante sur ressource de conformité Task

### ISSUE THREAD

**Issue by LudivineLacour** [ansforge/IG-fhir-repertoire-offre-ressources-sante#167]
# Description du problème
Dans la ressource conformité de Task, sur l'élément businessStatus, il manque l'apparition d'un Binding avec la référence à la NOS StatutMetier. Il y a par ailleurs des fautes dans la description existante.

# Fichier•s concerné•s
https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-task.html

# Solution proposée
Modification de la description comme ceci : 

> Différents types de statuts métier de l'anomalie. Binding: https://mos.esante.gouv.fr/NOS/JDV_J244-StatutMetierAnomalie-ROR/FHIR/JDV-J244-StatutMetierAnomalie-ROR ([required](http://hl7.org/fhir/R4/terminologies.html#required))

**Comment by sdemeyANS** [comment]
Correction visible ici https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-add-binding-task-statutmetier/StructureDefinition-ror-task.html
