### ISSUE TITLE
Pourquoi est-ce que cet IG réinvente la roue ?

### ISSUE THREAD

**Issue by LucChattyFyrstain** [ansforge/IG-fhir-repertoire-offre-ressources-sante#17]
Le profile IHE https://profiles.ihe.net/ITI/mCSD/artifacts.html aurait pu servir de base.
De plus, aucun des profils du ROR n'hérite d'aucun profil du FR CORE. Le ROR n'aurait-il vocation à n'être interopérable qu'avec lui même ?
Et je ne parle même pas de la liste à la Prevert des extensions qui sont plus la trace de mauvaises modélisations. Par exemple : ROROrganizationPrice : Il y a une ressource FHIR qui s'appelle ChargeItemDefinition et qui aurait pu a mon avis bien mieux convenir.

Cordialement,

**Comment by nriss** [comment]
Hello Luc,

Merci pour ton commentaire, nous avions bien entendu identifié mCSD et sommes conscients de l'usage excessif des extensions. Cependant, nous avons des contraintes projets (notamment en termes de délai et d'existant) qui ont nécessité ces compromis dans une première version.
 
Nous gardons cela dans notre backlog pour les prochaines versions. Nous fonctionnons avec une démarche d'amélioration continue, donc tous commentaires sont bons à prendre :-)

Concernant les profils fr-core, quels héritages sont manquants selon toi ? Organization hérite bien de fr-core
