### ISSUE TITLE
Syntaxe récupération des orgas via healthcare service

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#190]
# Description du problème
aujourdhui le ror utilise cette syntaxe : 
https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/HealthcareService?_include=HealthcareService:location&**_include=HealthcareService:providedBy&_include:iterate=Organization:partOf**&_include=PractitionerRole:practitioner&_revinclude=PractitionerRole:service

La syntaxe proposée dans l'iG est : 
GET [BASE]/HealthcareService?**_include:iterate=HealthcareService:organization**&_include=HealthcareService:location&_revinclude=PractitionerRole:service&_include=PractitionerRole:practitioner

# Solution proposée
Nous allons intégrer la syntaxe de l'IG dans le dev, mais on conservera également l'ancien mode d'appel

**Comment by paulineheurtebise** [comment]
Est ce que ce n'est pas la meme chose que dans cette issue #130

**Comment by jcserafini** [comment]
@paulineheurtebise yes c'est ca mais je retrouvais pas le sujet. Je vais le réouvrir car il y a un élément que je ne comprends pas.

**Comment by jcserafini** [comment]
Cf issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/130, je ferme cette issue ayant la réponse à ma question
