### ISSUE TITLE
Ajout de l'url du JDV-J238-TypeOffre-ROR

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-repertoire-offre-ressources-sante#194]
# Description du problème

L'url du JDV-J238-TypeOffre-ROR n'est pas renseignée

# Fichier•s concerné•s

[aliases.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/aliases.fsh)

# Solution proposée

Ajouter l'url quand le jdv sera créé

**Comment by sdemeyANS** [comment]
attente URL NOS

**Comment by PhilippeC-ANS** [comment]
C'est un loupé ; j'en demande la création pour le publication de janvier 2024.

**Comment by sly-kereval** [comment]
L'url a été ajoutée puisque le jdv va être créé prochainement.
