### ISSUE TITLE
Certains profils n'héritent pas des profils FrCore

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-repertoire-offre-ressources-sante#196]
# Description du problème
FrCore doit être la référence des profils français, pourquoi est-ce que ces ressources n'héritent pas des profils FrCore correspondants ?
- Location
- HealthcareService
- Practitioner (héritage de l'annuaire)
- PractitionerRole

A prévoir dans la roadmap produit pour rétablir l'héritage.

**Comment by sdemeyANS** [comment]
@nriss je lance une branche test https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/tree/test-heritage-fr-corepour voir déjà l'impact avec fr.core

**Comment by sdemeyANS** [comment]
preview visible ici https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/test-heritage-fr-core/artifacts.html

**Comment by sdemeyANS** [comment]
1er impact bloquant : l'héritage de FRLocation rend identifier obligatoire. on doit passer de 0..* à 1..*. @jcserafini est-ce que ce serait acceptable dans l'implementation du ROR National ?

**Comment by sdemeyANS** [comment]
@jcserafini et @nriss à arbitrer selon l'impact. Est-ce que l'on peut faire cette modification dans la prochaine version de l'IG ? (0.2.0

**Comment by sdemeyANS** [comment]
je mets en milestone 0.2.0 pour le moment pour mettre cette issue en évidence

**Comment by sdemeyANS** [comment]
autre impact à géré :
StructureDefinition-ror-healthcareservice.json 06:21:15
[-1, -1] StructureDefinition: Error - Binding https://mos.esante.gouv.fr/NOS/JDV_J17-ActiviteOperationnelle-ROR/FHIR/JDV-J17-ActiviteOperationnelle-ROR is not a subset of binding http://interopsante.org/fhir/ValueSet/fr-practitioner-specialty
[-1, -1] StructureDefinition: Error - Binding https://mos.esante.gouv.fr/NOS/JDV_J51-FamilleActiviteOperationnelle-ROR/FHIR/JDV-J51-FamilleActiviteOperationnelle-ROR is not a subset of binding http://interopsante.org/fhir/ValueSet/fr-practitioner-specialty

**Comment by sdemeyANS** [comment]
> As-tu comparé à la version publiée ou bien à la version en concertation de FrCore ? Pour info, on a fait le choix de ne pas hériter de PractitionerRole dans le cadre de l'Annuaire car celui-ci est trop contraignant

dépendance visible ici :) https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/test-heritage-fr-core/index.html#d%C3%A9pendances
pour la version fr.core en cours de build c'est une autre issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/195

**Comment by nriss** [comment]
C'est propre! Parfait merci :)

**Comment by sdemeyANS** [comment]
> 1er impact bloquant : l'héritage de FRLocation rend identifier obligatoire. on doit passer de 0..* à 1..*. @jcserafini est-ce que ce serait acceptable dans l'implementation du ROR National ?

@jcserafini

**Comment by sdemeyANS** [comment]
> autre impact à gérer : StructureDefinition-ror-healthcareservice.json 06:21:15 [-1, -1] StructureDefinition: Error - Binding https://mos.esante.gouv.fr/NOS/JDV_J17-ActiviteOperationnelle-ROR/FHIR/JDV-J17-ActiviteOperationnelle-ROR is not a subset of binding http://interopsante.org/fhir/ValueSet/fr-practitioner-specialty [-1, -1] StructureDefinition: Error - Binding https://mos.esante.gouv.fr/NOS/JDV_J51-FamilleActiviteOperationnelle-ROR/FHIR/JDV-J51-FamilleActiviteOperationnelle-ROR is not a subset of binding http://interopsante.org/fhir/ValueSet/fr-practitioner-specialty

@jcserafini

**Comment by sdemeyANS** [comment]
> healthcareservice

en complément :
aujourdhui 
<img width="488" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/ab40b0ce-e6df-43ed-bf30-3b21d910143c">

Avec héritage FR core:
<img width="487" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/4d8e9e2a-056a-48d8-b3bb-4c7696e0db04">
 on passe preferred à required
De plus je ne comprends pas pourquoi nous gardons le binding https://hl7.org/fhir/R4/valueset-c80-practice-codes.html plutot que celui de FR core https://simplifier.net/frenchprofiledfhirar/fr-practitioner-specialty qui Import all codes from CodeSystem https://mos.esante.gouv.fr/NOS/TRE_R38-SpecialiteOrdinale/FHIR/TRE-R38-SpecialiteOrdinale. PAr contre du coup d'après la modélisation de la SD il faudrait que https://mos.esante.gouv.fr/NOS/JDV_J51-FamilleActiviteOperationnelle-ROR/FHIR/JDV-J51-FamilleActiviteOperationnelle-ROR soit un subset dehttps://simplifier.net/frenchprofiledfhirar/fr-practitioner-specialty sauf erreur d'interprétation de ma part

**Comment by jcserafini** [comment]
@sdemeyANS la question est plus pour philippe non ? @PhilippeC-ANS

**Comment by paulineheurtebise** [comment]
Réunion 14/12 : 

- FRLocation rend identifier obligatoire. on doit passer de 0..* à 1..*.
-> ME pas obligatoire. D'un point de vue métier pas  un identifiant fonctionnel systèmatique
=> héritage à ne pas faire de suite. 

- FrPractitioner => héritage ok

- FRHealthcareService => pas tout de suite, trop contrainte avec le binding (issue côté InteropSanté)

**Comment by sdemeyANS** [comment]
> Réunion 14/12 :
> 
> * FRLocation rend identifier obligatoire. on doit passer de 0..* à 1..*.
>   -> ME pas obligatoire. D'un point de vue métier pas  un identifiant fonctionnel systèmatique
>   => héritage à ne pas faire de suite.
> * FrPractitioner => héritage ok
> * FRHealthcareService => pas tout de suite, trop contrainte avec le binding (issue côté InteropSanté)

Vu les blocages vu en réunion ce jour on dépriorise ce sujet et on n'intègre pas l'héritage pour la version 0.2.0

**Comment by sdemeyANS** [comment]
@PhilippeC-ANS @jcserafini @mathieu-decarvalho : pour information 2 issues créées côté fr.core suite à notre échange du 14/12

- https://github.com/Interop-Sante/hl7.fhir.fr.core/issues/100
- https://github.com/Interop-Sante/hl7.fhir.fr.core/issues/99

Avec des premiers éléments de réponse

**Comment by nriss** [comment]
Concernant HealthcareService.specialty, nous avons émis des doutes sur le changement, parce que specialty doit bien contenir les spécialités médicales qui sont proposées.
<img width="781" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/48218773/5ab184e3-adbe-4631-9074-34b7cdb04111">


Les champs utilisés dans "specialty" dans le ROR ressemblent davantage à un HealthcareService.type qu'à une spécialité :
<img width="1052" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/48218773/3bf6153c-c3b0-4b9f-9275-19103f85a64d">

Il vaut mieux à priori slicer HealthcareService.type pour y renseigner les trois données : champActivite (JDV J20), activiteOperationnelle (JDV J17) et familleActiviteOperationnelle (JDV J51)

P-être mettre une seule slice et deux codings pour activiteOperationnelle (JDV J17) et familleActiviteOperationnelle (JDV J51) ?

**Comment by sdemeyANS** [comment]
Bonjour,
Je propose de clore cette issue et de nous focaliser maintenant sur la nouvelle version fr.core => cf issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/195
@nriss ok pour toi?

**Comment by nriss** [comment]
ok :)
