### ISSUE TITLE
Paramètres non supportés par le serveur FHIR ROR N

### ISSUE THREAD

**Issue by isidacally** [ansforge/IG-fhir-repertoire-offre-ressources-sante#198]
# Description du problème
Nous souhaitons récupérer l'offre de l'activité opérationnelle "Réanimation spécialisée brûlés" code 121.
Mais le serveur FHIR renvoie une erreur lors de la réception de la requête ci-dessous : 
https://api.rortest.esante.gouv.fr/ws-diffusion-fhir-auth/HealthcareService?speciality=https://mos.esante.gouv.fr/NOS/TRE_R211-ActiviteOperationnelle/FHIR/TRE-R211-ActiviteOperationnelle|121&_include:iterate=HealthcareService:organization&_include=HealthcareService:location&_revinclude=PractitionerRole:service&_include=PractitionerRole:practitioner

Retour du serveur FHIR ROR-N : 
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "not-supported",
            "diagnostics": "Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[HealthcareService] with parameters [[_include, _include:iterate, speciality, _revinclude]]"
        }
    ]
}

Pour info la requête provient de l'IG ROR national.

# Fichier•s concerné•s

# Solution proposée

**Comment by RomainCaraty** [comment]
Bonjour @isidacally,

Le paramètre doit être specialty sans "i".
Il est prévu de corriger cette requête sur l'IG. 

LA requête doit être donc https://api.rortest.esante.gouv.fr/ws-diffusion-fhir-auth/HealthcareService?specialty=https://mos.esante.gouv.fr/NOS/TRE_R211-ActiviteOperationnelle/FHIR/TRE-R211-ActiviteOperationnelle|121&_include:iterate=HealthcareService:organization&_include=HealthcareService:location&_revinclude=PractitionerRole:service&_include=PractitionerRole:practitioner](https://api.rortest.esante.gouv.fr/ws-diffusion-fhir-auth/HealthcareService?speciality=https://mos.esante.gouv.fr/NOS/TRE_R211-ActiviteOperationnelle/FHIR/TRE-R211-ActiviteOperationnelle%7C121&_include:iterate=HealthcareService:organization&_include=HealthcareService:location&_revinclude=PractitionerRole:service&_include=PractitionerRole:practitioner)

**Comment by sdemeyANS** [comment]
bonjour
typo corrigée dans la prochaine version en cours de construction. Visible dans la ci-build : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_3.html

**Comment by sdemeyANS** [comment]
Bonjour @isidacally 
Est-ce que notre réponse répond bien à votre demande ?
Pouvons nous clore l'issue?

**Comment by isidacally** [comment]
Bonjour,

Oui merci la requête fonctionne :)
Je ferme l'issue.

Cordialement
