### ISSUE TITLE
[narratif] 1er tableau cas d'usage spec technique

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-repertoire-offre-ressources-sante#201]
# Description du problème
Ce tableau n'a plus de sens dans l'IG
<img width="548" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/eac1f8c1-0d3a-484c-8332-b35e923ab5ec">

# Fichier•s concerné•s
pages specs_techniques

# Solution proposée
supprimer le tableau ou conserver que les 2/3 1eres lignes

**Comment by sdemeyANS** [comment]
@jcserafini on peut afficher le endpoint de prod dans l'IG ?.
Pour l'encodage que met-on si besoin de le remplir?
De mon point de vu les 3 dernières lignes non plus d'intérêt dans l'IG

**Comment by nriss** [comment]
Je suis aligné!

**Comment by jcserafini** [comment]
@sdemeyANS on ne préfère pas afficher l'URL de prod. L'encodage est UTF-8

**Comment by paulineheurtebise** [comment]
Réunion 14/12 : Ok pour supprimer le tableau complet.
