### ISSUE TITLE
Ajout cas d'usage saisie de l'offre

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-repertoire-offre-ressources-sante#203]
Ajout des cas d'usage liés à la saisie de l'offre

**Comment by paulineheurtebise** [comment]
Preview version intermédiaire au 15/12 : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/

**Comment by jcserafini** [comment]
Hello 
A la relecture on se rend compte que le scénario de modification d'une offre sur de multiples informations aurait du sens, en particulier coté IHM ou on va certainement effectuer les modifications en bloc sur base de ce qui a été modifié par l'utilisateur:
Exemple:
L'utilisateur a ajouté 1 activités opérationnelles + ajout 1 acte spé + ajout un contact avec son numéro + modifie ses horaires  et valide la saisie -> dans ce cas vaut il mieux faire n PATCH ou 1 seul PUT avec toutes les infos ?

**Comment by paulineheurtebise** [comment]
Hello @jcserafini, 
Est ce que [le scénario 8](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_13.html#sc%C3%A9nario-8-modification-dune-offre-op%C3%A9rationnelle-pr%C3%A9cision-sur-loffre-op%C3%A9rationnelle-dun-cabinet-de-ville) ne répond il pas déjà au besoin ? 
Nous pouvons le compléter avec le numéro du contact et les horaires ?
