### ISSUE TITLE
Souci type fermeture Organization

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#204]
# Description du problème
Nous constatons des soucis sur le type fermeture d'une organization.
Si on regarde la donnée ici : 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-organization.html
la description dit : "Date prévisionnelle à partir de laquelle la prestation sera de nouveau assurée" -> cela me parait incorrect.

Ensuite si on regarde sur le critère de recherche : 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/search_param.html
La définition dit : 
"Type de fermeture de l'entité géographique, au sens des règles de gestion du SI FINESS (par exemple: fermeture définitive, fermeture provisoire)."

Est ce que ce critère est utilisable sur les EJ, EG et OI aussi ? La donnée en tout cas semble être la même "typeFermeture (EJ + EG + OI) "

Enfin (plus une question ici) le MEV3 indique qu'il faut utiliser : 
TRE_R286-TypeFermeture pour les EJ et EG
JDV_J185-typeFermeture-ROR pour les OI

l'IG indique https://mos.esante.gouv.fr/NOS/JDV_J201-TypeFermeture-ROR/FHIR/JDV-J201-TypeFermeture-ROR

Est ce normal ?
@PhilippeC-ANS jme permet de te tag sur cette issue

**Comment by sdemeyANS** [comment]
> Concernant le 1er point, il s'agit selon moi d'une coquille documentaire. La définition reportée en face de "type de fermeture" correspond à celle de "date prévisionnelle de réouverture".
> 
> Concernant le 2e point, il y a une explication liée à l'enchainement des actions, mais pas vraiment d'attente métier.
> 
> * Pour l'EJ et l'EG, le MOS s'appuie directement sur la TRE R286.
>   Le modèle d'exposition ROR a repris ce principe et cite également la TRE R286 ; Au moment où l'on nous a demandé de créer un JDV pour chaque TRE utilisée, nous avons créé le JDV J201.
> * pour l'OI nous avons adopté un JDV "ROR" (le J185) afin de limiter les valeurs qui peuvent être utilisées (uniquement Définitif ou temporaire). Ces codes proviennent également de la TRE R286.
> 
> Donc 2 jeux de valeurs basés sur la même TRE, mais on pourrait n'en avoir qu'un seul si cela est plus simple.

- [ ] point 1 à corriger dans l'IG
- [ ] point 2 @jcserafini il faut le traiter maintenant ou plus tard ? impact dev ?

**Comment by sly-kereval** [comment]
Le 1er point a été traité.

Concernant le 2eme point, voici un récap : 
* Actuellement dans le modèle d'expo pour le type de fermeture : 
  * EJ : TRE R286
  * EG : TRE R286
  * OI : JDV J185 (reprend certains codes de la TRE286)
* Dans la structure definition de ROROrganization, le type de fermeture est mappé sur l'extension ror-organization-closing-type avec le JDV J201 qui reprend tous les codes de la TRE R286. 

Ce qui est fait actuellement est donc correct mais ne restreint pas les codes possibles dans le cas d'une OI. Est-ce que cela convient ou est-ce qu'il est nécessaire d'envisager des modifications pour traiter ce point ?

**Comment by jcserafini** [comment]
@PhilippeC-ANS @sdemeyANS @sly-kereval 
Je ne peux pas estimer l'impact dev, j'ai l'impression qu'on n'a pas tranché le sujet non ?

**Comment by paulineheurtebise** [comment]
Réunion 14/12 : 

- L'IG ne dit pas actuellement les codes autorisés pour l'OI. 
- Possible de s'appuyer sur la liste complète et créer une règle de gestion. Le but des JDV de porter cette restrictions ? 
- On traite le point plus tard, version semaine pro reste dans le même. 
- Dé-priorise, on enlève de la 0.2.0
- Chercher pour indiquer dans la SD la contrainte pour le POST ? comment c'est traité ? Règle de saisie ?

**Comment by mlr-kereval** [comment]
**Contexte :**
Pour rappel, la problématique restante sur ce ticket concerne le JDV associé à l'attribut FHIR pour le typeFermeture EJ, EG et OI ([profil ROROrganization](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/StructureDefinition-ror-organization.html)).
 
Actuellement le JDV associé à l'attribut FHIR [ror-organization-closing-type](https://interop.esante.gouv.fr/ig/fhir/ror/0.3.0/StructureDefinition-ror-organization-closing-type.html) qui représente le typeFermeture à la fois pour EJ, EG et OI est le [JDV_J201-TypeFermeture-ROR](https://mos.esante.gouv.fr/NOS/JDV_J201-TypeFermeture-ROR/FHIR/JDV-J201-TypeFermeture-ROR/) qui reprend tous les codes de la [TRE_R286-TypeFermeture](https://mos.esante.gouv.fr/NOS/TRE_R286-TypeFermeture/TRE_R286-TypeFermeture.pdf).
 
Cependant, d'après le MEV3, seuls certains codes de la [TRE_R286-TypeFermeture](https://mos.esante.gouv.fr/NOS/TRE_R286-TypeFermeture/TRE_R286-TypeFermeture.pdf) sont autorisés dans le cas de l'OI : ceux présents dans le [JDV_J185-typeFermeture-ROR](https://mos.esante.gouv.fr/NOS/JDV_J185-TypeFermeture-ROR/JDV_J185-TypeFermeture-ROR.pdf).
 
Or cette information n'est pas présente dans l'IG.
 
**Proposition :** 
Créer une règle de gestion pour préciser que lorsque la ressource Organization est une OI, les valeurs pour le typeFermeture sont restreintes à DEF (Définitive) ou PRO (Provisoire).
 
**Problématique :** 
La ressource [ROROrganization](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/StructureDefinition-ror-organization.html) étant partagée entre OI/EG/EJ, pour mettre en place cette règle de gestion, il est nécessaire de se baser sur la présence d'un élément caractéristique de l'OI. 
 
Cependant, aucun élément obligatoire permet de distinguer le type d'Organization : EJ/EG/OI. 
 
_Proposition 1 :_ Rendre obligatoire l'élément type [1..*] : 
•	Pour l'EG, le slice categorieEtablissement est requis par le ME (categorieEG)
•	Pour l'EJ, le slice statutJuridiqueINSEE est requis par le ME (statutJuridique)
•	Pour l'OI, le slice OIType est requis par le ME (typeOI)
Ces contraintes n'apparaissent pas dans l'IG. Il faudrait donc accompagner le changement de cardinalité sur l'élément type d'une règle de gestion afin d'imposer l'utilisation du slice categorieEtablissement ou statutJuridiqueINSEE ou OIType.
 
_Proposition 2 :_ Rendre le slice organizationType hérité de la ressource FrOrganization requis et supprimer le slice OIType 
Ce sujet est en partie abordé dans l'issue #298

**Comment by sdemeyANS** [comment]
problème de définition type de fermeture corrigé : https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/353

**Comment by sdemeyANS** [comment]
> Le 1er point a été traité.
> 
> Concernant le 2eme point, voici un récap :
> 
> * Actuellement dans le modèle d'expo pour le type de fermeture :
>   
>   * EJ : TRE R286
>   * EG : TRE R286
>   * OI : JDV J185 (reprend certains codes de la TRE286)
> * Dans la structure definition de ROROrganization, le type de fermeture est mappé sur l'extension ror-organization-closing-type avec le JDV J201 qui reprend tous les codes de la TRE R286.
> 
> Ce qui est fait actuellement est donc correct mais ne restreint pas les codes possibles dans le cas d'une OI. Est-ce que cela convient ou est-ce qu'il est nécessaire d'envisager des modifications pour traiter ce point ?

Reste le 2eme point à traiter dans cette issue
