### ISSUE TITLE
Zone intervention

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#21]
Pour rechercher sur une zone d'intervention la syntaxe proposée dans le docX est get[BASE]/HealthcareService?location.intervention-zone=XXX .
L'intervention zone est une extension complexe avec 2 codeable concept type, code. Est il possible de rechercher en précisant les types , les codes ... si oui quelle syntaxe adopter ?

**Comment by nriss** [comment]
L'expression indique où est-ce que le paramètre de recherche cherche : https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/instances/ror-sp-healthcareservice-intervention-zone.fsh
Ici : HealthcareService.extension.where(url='https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-territorial-division').extension(url='typeTerritorialDivision').valueCodeableConcept

**Comment by nriss** [comment]
1. Revoir le nom de l'extension : https://interop.esante.gouv.fr/ig/fhir/ror/ValueSet-code-region-territorial-division.html
2. Changer le SearchParam pour chercher dans le code et pas dans le type @sdemeyANS

**Comment by nriss** [comment]
> 2\. pas dans le type

Ca me va :)
Attendons le go de @sdemeyANS

**Comment by sdemeyANS** [comment]
> > 2. pas dans le type
> 
> Ca me va :) Attendons le go de @sdemeyANS

OK pour point 2

**Comment by nriss** [comment]
Mon point concernait surtout le nom du ValueSet qui ne va pas : https://interop.esante.gouv.fr/ig/fhir/ror/ValueSet-code-region-territorial-division.html
Car il fusionne 5 VS et s'appelle "Fusion du valueset J223-TypeDivisionTerritoriale-ROR et JDV_J237-RegionOM-ROR"

**Comment by sly-kereval** [comment]
En effet, c'est corrigé. 

J'ai également remarqué une erreur dans la requête : get[BASE]/HealthcareService?location.intervention-zone=XXX.
Le "location" n'est pas nécessaire car le search param intervention-zone s'applique directement à HealthcareService. 
Ce sera corrigé dans la prochaine version de la spécification que nous allons vous transmettre.
