### ISSUE TITLE
Quand sera disponible le MEV3 du ROR en accès public ? 

### ISSUE THREAD

**Issue by flachalESEA** [ansforge/IG-fhir-repertoire-offre-ressources-sante#217]
# Description du problème
Il me semble important que le document MEV3 ([Ref_01] ROR – Modèle d’exposition | 3.0 | Description des données communes aux échanges entre les ROR et les SI externes. (lien bientôt disponible)) soit publié et accessible de manière publique afin que les industriels puissent sereinement mesurer leur intérêt d'accéder au ROR National

# Fichier•s concerné•s
Page d'accueil de l'IG

# Solution proposée

**Comment by sdemeyANS** [comment]
Bonjour,
cf issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/182

**Comment by flachalESEA** [comment]
Sorry Sylvain, j'avais pas été cherché :'(

**Comment by sdemeyANS** [comment]
pas de souci :)

**Comment by sdemeyANS** [comment]
je clos du coup. la suite ici :) https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/182
