### ISSUE TITLE
Typo url TRE R345

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-repertoire-offre-ressources-sante#219]
# Description du problème

Dans le profil ROROrganization, l'url de la TRE pour type.coding.system du slice identifierOI n'est pas valide : https://mos.esante.gouv.fr/NOS/TRE_R345-TypeIdentifiantAutre/FHIR/TRE_R345-TypeIdentifiantAutre au lieu de https://mos.esante.gouv.fr/NOS/TRE_R345-TypeIdentifiantAutre/FHIR/TRE-R345-TypeIdentifiantAutre

# Fichier•s concerné•s

[aliases.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/aliases.fsh)

# Solution proposée

Corriger l'alias

**Comment by sdemeyANS** [comment]
@jcserafini  pour info
