### ISSUE TITLE
availableTime cardinalité extension

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-repertoire-offre-ressources-sante#221]
# Description du problème

L'extension ror-available-time-number-days-of-week de HealthcareService.availableTime est-elle réellement nécessaire puisque l'élément availableTime.daysOfWeek, de type code et de cardinalité 0..*, permet de renseigner les jours de la semaine ? 

Pour information, dans le ME cette extension correspond à l'attribut jourSemaine (de type numérique et de cardinalité 0..1) de la classe Horaire, qui est le type de l'attribut horaire (cardinalité 0..*) de la classe OffreOperationnelle. 

S'il est nécessaire de conserver l'extension ror-available-time-number-days-of-week, la cardinalité doit être revue. En effet, les cardinalités de l'extension et de l'élément availableTime, ne permettent de renseigner qu'un seul numéro de jour dans la semaine.

![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/125375447/77121a8d-cdab-4408-abd7-afc8e4b7ff6e)

# Fichier•s concerné•s

[ROROrganization.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/profiles/ROROrganization.fsh)
[RORAvailableTimeNumberDaysofWeek.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/extensions/RORAvailableTimeNumberDaysofWeek.fsh)

# Solution proposée

Déterminer la nécessité de l'extension pour ensuite définir les cardinalités si besoin.

**Comment by PhilippeC-ANS** [comment]
Pas de besoin métier identifié de mon côté sur l'utilisation de l'un plutôt que de l'autre.

**Comment by loic-brtd** [comment]
Bonjour, j'allais poser la même question 😄

Dans l'implémentation du ror national, j'ai remarqué qu'on avait peuplé d'une part le champ `daysOfWeek` sur les PractitionerRole et d'autre part l'extension `ror-available-time-number-days-of-week` sur les HealthcareSercive.

Je me demandais le quel conserver ou s'il fallait peupler les deux champ.

**Comment by paulineheurtebise** [comment]
Réunion du 25/01/24 : 
Privilégier si possible l'usage de l'attribut natif, mais c'est une modification du format (impact sur le ME). 
En cours de validation coté ROR (mail à Mathieu 26/01)

**Comment by paulineheurtebise** [comment]
Proposition n°1 : Extension uniquement
availableTime en cardinalité 0..* (natif) + utilisation de l'extension ror-available-time-number-days-of-week 0..1 + retirer la possibilité d'utiliser daysOfWeek 0..0

Proposition n°2 : Attribut natif uniquement
availableTime en cardinalité 0..* (natif) + suppression de l'extension ror-available-time-number-days-of-week + utiliser daysOfWeek 0..1

Proposition n°1 : Extension + Natif possible
availableTime en cardinalité 0..* (natif) + utilisation de l'extension ror-available-time-number-days-of-week 0..1 + utiliser daysOfWeek 0..1

**Comment by paulineheurtebise** [comment]
Atelier 14/02 : 
Choix de la proposition n°3 + indiquer dans le narratif que nous privilégions pour le moment l'utilisation de l'extension à l'attribut natif daysOfWeek

**Comment by sly-kereval** [comment]
Modification réalisée suite au choix de la proposition

Preview : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/

**Comment by jcserafini** [comment]
@sdemeyANS @Mathieu-Rousseau vu que cela bloque la correcte diffusion des horaires je propose de passer ça dans la prochaine version. On doit le dév en 3.2

**Comment by sdemeyANS** [comment]
> @sdemeyANS @Mathieu-Rousseau vu que cela bloque la correcte diffusion des horaires je propose de passer ça dans la prochaine version. On doit le dév en 3.2

la prochaine version de l'IG cible 3.1 par contre?

**Comment by jcserafini** [comment]
@sdemeyANS ça a pas l'air d'être le bon lien vers la preview , vous avez le bon lien svp ?
