### ISSUE TITLE
supprimer le critère de recherche sur les devises des tarifs

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-repertoire-offre-ressources-sante#225]
# Description du problème
Il faut supprimer le critère de recherche sur les devises des tarifs. Le ROR n’utilise que l’euro, il n’est pas prévu de conversion
suite réunion vision produit 06/12

# Fichier•s concerné•s

# Solution proposée
supprimer le critère et sa référence dans le narratif

**Comment by sdemeyANS** [comment]
@jcserafini pour info issue créé suite à la réunion vision produit du 6/12
pour quelle version de l'IG cela doit être traité ?

**Comment by jcserafini** [comment]
@sdemeyANS tu peux l'enlever partout, nous ne l'avons jamais développé

**Comment by sdemeyANS** [comment]
> @sdemeyANS tu peux l'enlever partout, nous ne l'avons jamais développé

OK on traite pour la prochaine version de l'IG alors

**Comment by sdemeyANS** [comment]
pour le narratif peut être le faire directement dans la branche https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/tree/sd-add-version-ROR-N

**Comment by sly-kereval** [comment]
Le paramètre de recherche est-il supprimé définitivement ou seulement pas applicable pour le moment ?  

Voici les impacts :  
- Dans le cas de la suppression du SP :
  - CapabalityStatement : [ror-consommateur.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/instances/ror-consommateur.fsh) et [ror-serveur.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/instances/ror-serveur.fsh)  --> supprimer le SP
  - Fichier fsh du SP : [ror-sp-organization-price-amount-currency.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/instances/ror-sp-organization-price-amount-currency.fsh) --> supprimer le fichier
  - Tableau des SP : [search_param.md](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/pagecontent/search_param.md) --> supprimer le SP
  - Spécifications techniques du cas d'usage Recherche d'offre sur la base d'informations tarifaires : [specifications_techniques_8.md](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/pagecontent/specifications_techniques_8.md) --> Supprimer le SP du tableau et les critère de recherche dans les exemples de requêtes
 - Dans le cas où le SP n'est pas applicable pour le moment
   - CapabalityStatement : [ror-consommateur.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/instances/ror-consommateur.fsh) et [ror-serveur.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/instances/ror-serveur.fsh)  --> commenter le SP
   - Fichier fsh du SP : [ror-sp-organization-price-amount-currency.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/instances/ror-sp-organization-price-amount-currency.fsh) --> pas d'impact
   - Tableau des SP : [search_param.md](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/pagecontent/search_param.md) --> indiquer comme applicable ultérieurement 
   - Spécifications techniques du cas d'usage Recherche d'offre sur la base d'informations tarifaires : [specifications_techniques_8.md](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/pagecontent/specifications_techniques_8.md) --> indiquer le critère sera applicable ultérieurement
  
@sdemeyANS je fais toutes les modifs (selon la réponse à la question) sur la branche https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/tree/sd-add-version-ROR-N ou seulement celles qui concernent le narratif ?

**Comment by sdemeyANS** [comment]
Bonjour,

Comme vu avec @jcserafini le critère de recherche ne sera pas implémenté. Pas de conversion de devise prévue dans le ROR National
On peut tout faire sur https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/tree/sd-add-version-ROR-N puisque que cela reste cohérent avec l'objet de cette branche IG vs Implémentation dans la solution ROR N.

Concernant : 
Spécifications techniques du cas d'usage Recherche d'offre sur la base d'informations tarifaires : [specifications_techniques_8.md](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/pagecontent/specifications_techniques_8.md) --> Supprimer le SP du tableau et les critère de recherche dans les exemples de requêtes => pas besoin. Comme vu hier ces tableaux vont être retiré pour renvoyer vers la page search_param
