### ISSUE TITLE
Incohérence format Adresse StreetNameType

### ISSUE THREAD

**Issue by LudivineLacour** [ansforge/IG-fhir-repertoire-offre-ressources-sante#229]
# Description du problème
L'IG indique sur la ressource de conformité Organization un attribut de la classe adresse StreetNameType qui a un format string alors qu'il y a référence à une NOS dans la description et que le mapping FHIR en .xlsx indique que le format de cet attribut est un codeable concept.

Pouvez-vous me dire quel format est le bon _string_ ou _codeable concept_ ? 

# Fichier•s concerné•s
https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-organization.html

# Solution proposée
Corriger le format sur la page selon le format correct

**Comment by paulineheurtebise** [comment]
Effectivement dans le mapping le type de donnée n'est pas le bon. 
C'est bien un string à qui on associe un jeu de valeur. C'est un mécanisme décrit paragraphe[ 4.1.6.1 de la page des terminologies](https://fhir-ru.github.io/terminologies.html#strings). 

Je modifie le mapping pour Organization et Location.

**Comment by paulineheurtebise** [comment]
Preview disponible : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/229-incoherence-format-adresse-streetnametype/mapping.html

**Comment by paulineheurtebise** [comment]
Pourquoi est ce que le type de donnée est string ? 
Pour les lignes de l'adresse nous utilisons des extensions publiées par HL7. 
Le type de voie souhaité correspond à l'extension [streetnametype](http://hl7.org/fhir/R4/extension-iso21090-adxp-streetnametype.html). Cette extension est de type string. Pour les besoins du ROR nous avons associé un VS à cet attribut.

**Comment by LudivineLacour** [comment]
> Pourquoi est ce que le type de donnée est string ? Pour les lignes de l'adresse nous utilisons des extensions publiées par HL7. Le type de voie souhaité correspond à l'extension [streetnametype](http://hl7.org/fhir/R4/extension-iso21090-adxp-streetnametype.html). Cette extension est de type string. Pour les besoins du ROR nous avons associé un VS à cet attribut.

@paulineheurtebise  je ne comprends pas comment le Value Set est-il censé être diffusé par les implémenteurs et récupéré par les consommateurs ?
