### ISSUE TITLE
System RPPS rang - Site inaccessible

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#233]
# Description du problème
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-organization.html
Sur l'identifiant rpps rang, l'adresse suivante est indiquée dans le system : http://rppsrang.esante.gouv.fr
Cette adresse n'amène nulle part est ce normal ?

# Fichier•s concerné•s

# Solution proposée

**Comment by sdemeyANS** [comment]
C'est ne lien avec https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/83#issuecomment-1807679395

**Comment by sdemeyANS** [comment]
sauf erreur ces liens sont renseignés en attendant qu'ils soient "actifs" (redirections?) vu que le system est en 1..1

**Comment by sdemeyANS** [comment]
@jcserafini je peux enlever milestone 0.2.0 ?

**Comment by sdemeyANS** [comment]
on peut clore je pense cette issue suite au traitement de celle-ci https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/348
