### ISSUE TITLE
IG- Extraction complète du capacitaire : Scénario 1

### ISSUE THREAD

**Issue by RomainCaraty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#237]
Bonjour @sdemeyANS,

Comme vu ensemble il faut que le scénario 1 de l'Extraction complète du capacitaire apparaisse sur l'IG https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_2.html avec l'exemple suivant :

►	Scénario 1 : Un consommateur souhaite mettre à jour toutes les données capacitaires sur le périmètre national (Faire une extraction complète sur les LOCATIONS 3.0 avec une pagination de 200 résultats par page)

Requête : https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/Location?_revinclude=HealthcareService:location

**Comment by sly-kereval** [comment]
Le narratif est mis à jour :
- maj de la description du scénario avec les valeurs de l'issue

Preview disponible : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/narratif-scenario-retour-platine-2 

Remarques : 
- Le scénario 1bis a été également été mis à jour pour la cohérence.
- La précision entre parenthèses "Faire une extraction complète sur les LOCATIONS 3.0 avec une pagination de 200 résultats par page" n'a pas été ajoutée car ce type d'information n'est pas présent dans les autres scénarios.

**Comment by sdemeyANS** [comment]
ok attente validation PR https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/282

**Comment by paulineheurtebise** [comment]
14/02 - Romain/Sylvain/Kereval : ok
