### ISSUE TITLE
IG- Recherche d'offre sur critères principaux : Scénario 6 bis

### ISSUE THREAD

**Issue by RomainCaraty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#244]
Bonjour @sdemeyANS,

Comme vu ensemble il faut que le scénario 6bis de recherche d'offre sur critères principaux apparaisse sur l'IG (https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_3.html) avec l'exemple suivant :

►	Scenario 6 bis: Recherche à proximité géographique
•	Un consommateur cherche les offres ayant une activité opérationnelle particulière, dans un périmètre géographique proche du lieu de résidence d'un patient.
Exemple : recherche des offres caractérisées par l’activité opérationnelle « 013 – Cardiologie générale », située dans un rayon de 1,5 kilomètres autour de Saint-Herblain (coordonnées géographiques d’un point de la commune)

Requête : https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/HealthcareService?specialty=https://mos.esante.gouv.fr/NOS/TRE_R211-ActiviteOperationnelle/FHIR/TRE-R211-ActiviteOperationnelle|013&location.near=47.21827323906432|-1.6369631507460436|1.5|km&_include:iterate=HealthcareService:organization&_include=HealthcareService:location&_revinclude=PractitionerRole:service&_include=PractitionerRole:practitionerole:practitioner&_include=HealthcareService:providedBy&_include:iterate=Organization:partOf

**Comment by sdemeyANS** [comment]
Bonjour @RomainCaraty on est d'accord c'est bien un scenario supplémentaire ?

**Comment by RomainCaraty** [comment]
Hello @sdemeyANS oui c'est bien le cas

**Comment by paulineheurtebise** [comment]
Ajout du scenario dans le narratif. 
Preview : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/ajout-scenario

Remarque : Attention je pense que dans la requête indiquée dans l'issue les _include ne sont pas corrects

**Comment by paulineheurtebise** [comment]
Bonjour @jcserafini, 
Comme c'est un nouveau scénario, est ce que tu peux nous dire quel label nous devons associer à ce scénario ? Draft ?
Merci !

**Comment by paulineheurtebise** [comment]
Hello @jcserafini et @RomainCaraty, est ce que je dois mettre le scenario en draft ? 
Merci !

**Comment by RomainCaraty** [comment]
Bonjour @sdemeyANS @paulineheurtebise,

les include et revinclude seront corrigés dans la V3.1 du ROR national.
Le scénario sera donc à mettre à jour avec la bonne requête.

Néanmoins ce scénario fait partie de la V2.3 du ROR national. Il faut donc le faire apparaitre dès aujourd'hui.

Merci.

**Comment by sdemeyANS** [comment]
> Bonjour @sdemeyANS @paulineheurtebise,
> 
> les include et revinclude seront corrigés dans la V3.1 du ROR national. Le scénario sera donc à mettre à jour avec la bonne requête.
> 
> Néanmoins ce scénario fait partie de la V2.3 du ROR national. Il faut donc le faire apparaitre dès aujourd'hui.
> 
> Merci.

Il a été demandé que la prochaine version de l'IG indique ROR 3.1 vu que c'est 2.3 j'imagine donc que nous devons pas mettre draft

**Comment by mlr-kereval** [comment]
Bonjour @jcserafini, @RomainCaraty, 

Faut-il retirer le label "draft" du scénario 6bis ?

**Comment by paulineheurtebise** [comment]
@jcserafini et @RomainCaraty
Faut-il retirer le label "draft" du scénario 6bis ? 
Merci !

**Comment by RomainCaraty** [comment]
Bonjour @sdemeyANS

la requête à faire afficher sur l'IG pour ce scénario en V2.3 est la suivante :

https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/HealthcareService?specialty=https://mos.esante.gouv.fr/NOS/TRE_R211-ActiviteOperationnelle/FHIR/TRE-R211-ActiviteOperationnelle|013&location.near=47.21827323906432|-1.6369631507460436|1.5|km&_include:iterate=HealthcareService:organization&_include=HealthcareService:location&_revinclude=PractitionerRole:service&_include=PractitionerRole:practitioner&_include=HealthcareService:providedBy&_include:iterate=Organization:partOf

**Comment by RomainCaraty** [comment]
Bonjour @sdemeyANS @paulineheurtebise

La requête utilisée en 3.1 est la suivante :

https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/HealthcareService?specialty=https://mos.esante.gouv.fr/NOS/TRE_R211-ActiviteOperationnelle/FHIR/TRE-R211-ActiviteOperationnelle|013&location.near=47.21827323906432|-1.6369631507460436|1.5|km&_include=HealthcareService:location&_revinclude=PractitionerRole:service&_include=PractitionerRole:practitioner&_include=HealthcareService:organization&_include:iterate=Organization:partof

On en rediscute aujourd'hui !

**Comment by paulineheurtebise** [comment]
Réunion 15/02 : Retirer le draft

**Comment by paulineheurtebise** [comment]
Ajouté sans le draft, j'ai mis 15 km au lieu de 1,5km pour avoir les mêmes valeurs que le scenario 6 sur near-insee-code : [Scénario 6 bis ajouté](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/narratif-scenario-retour-platine/specifications_techniques_3.html#sc%C3%A9nario-6-recherche-%C3%A0-proximit%C3%A9-g%C3%A9ographique)

**Comment by paulineheurtebise** [comment]
Issue fermée par la PR #267
