### ISSUE TITLE
Scénario 2 : Synchronisation Extraction des l’ensemble des offres de santé d’un établissement

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-repertoire-offre-ressources-sante#25]
Requête : 
get[BASE]/HealthcareService?organizationprovidedByorganization:above.:identifier=XX**&**_include:iterate=HealthcareService:organization&_include=HealthcareService:location&_revinclude=PractitionerRole:service&_include=PractitionerRole:practitioner

L'esperluette est oublié

**Comment by sly-kereval** [comment]
Cet oubli sera corrigé dans la prochaine version des spécifications qui sera livrée (suite à la prise en compte des retours).
