### ISSUE TITLE
IG- Consultation d'anomalie : Scénario 1

### ISSUE THREAD

**Issue by RomainCaraty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#253]
Bonjour @sdemeyANS,

Comme vu ensemble il faut que le scénario 1 de consultation d'anomalie apparaisse sur l'IG https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_7.html avec l'exemple suivant :

►	Scenario 1 : Consultation du statut d’une anomalie
•	Un responsable qualité ou un système numérique consommateur souhaite consulter le statut d’une anomalie.
Exemple : recherche de l’anomalie ayant pour id 687

Requête : GET https://rortest.esante.gouv.fr/anomalies/Task/687

**Comment by sly-kereval** [comment]
Bonjour @RomainCaraty,

Actuellement, la requête du scénario 1 utilise l'identifiant fonctionnel (identifier) : 
`GET [BASE]/Task?identifier=XXX`

Pour rechercher une recherche une ressource à partir de son identifiant technique (_id), il y a 2 possibilités : 
- Utiliser le critère de recherche _id (interaction search)
`GET [BASE]/Task?_id=XXX`
- Utiliser la syntaxe proposée ici (interaction read) : 
`GET [BASE]/Task/XXX`

Quelle syntaxe devons nous utiliser dans le scénario ?

**Comment by RomainCaraty** [comment]
Bonjour @sdemeyANS 

Merci d'utiliser la requête du scénario pour l'IG correspondant à la V2.3 du ROR national.

**Comment by sdemeyANS** [comment]
> Bonjour @sdemeyANS
> 
> Merci d'utiliser la requête du scénario pour l'IG correspondant à la V2.3 du ROR national.

Bonsoir. cad?

**Comment by sdemeyANS** [comment]
> Bonjour @RomainCaraty,
> 
> Actuellement, la requête du scénario 1 utilise l'identifiant fonctionnel (identifier) : `GET [BASE]/Task?identifier=XXX`
> 
> Pour rechercher une recherche une ressource à partir de son identifiant technique (_id), il y a 2 possibilités :
> 
> * Utiliser le critère de recherche _id (interaction search)
>   `GET [BASE]/Task?_id=XXX`
> * Utiliser la syntaxe proposée ici (interaction read) :
>   `GET [BASE]/Task/XXX`
> 
> Quelle syntaxe devons nous utiliser dans le scénario ?

@jcserafini les 3 sont dispos?

**Comment by sly-kereval** [comment]
Le narratif est mis à jour :
- maj de la description du scénario avec les valeurs de l'issue
- maj de la requete
- ajout de l'interaction read dans le tableau "Construction de la requête de base"

Preview disponible : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ajout-scenario/ig/

**Comment by RomainCaraty** [comment]
Bonjour @sdemeyANS

Je ne vois pas ce scénario affiché sur l'IG pour la V2.3 du ROR national.

**Comment by paulineheurtebise** [comment]
Réunion 15/02 : pas en draft

**Comment by paulineheurtebise** [comment]
Validée par la PR #282
