### ISSUE TITLE
IG- Consultation d'anomalie : Scénario 2

### ISSUE THREAD

**Issue by RomainCaraty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#254]
Bonjour @sdemeyANS,

Comme vu ensemble il faut que le scénario 2 de consultation d'anomalie apparaisse sur l'IG https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_7.html avec l'exemple suivant :

►	Scenario 2 : Consultation de la liste des anomalies
•	Un responsable qualité ou un système numérique consommateur souhaite consulter la liste des anomalies.
Exemple : recherche de la liste des anomalies sans élément précis

GET https://rortest.esante.gouv.fr/anomalies/Task

**Comment by sly-kereval** [comment]
Bonjour @RomainCaraty, 

Le scénario décrit correspond plutôt au scénario 4 : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_7.html#sc%C3%A9nario-4-consommation-de-toutes-les-anomalies

Faut-il modifier la description du scénario 4 avec les informations fournies dans cette issue ?

**Comment by paulineheurtebise** [comment]
@RomainCaraty Est ce que nous modifions le scénario 4 ?

**Comment by RomainCaraty** [comment]
Bonjour @sdemeyANS

Je ne vois pas ce scénario affiché sur l'IG pour la V2.3 du ROR national.

**Comment by paulineheurtebise** [comment]
Réunion 15/02 : ok traité par le scénario 4
