### ISSUE TITLE
IG- Signalement d'anomalie : Scénario 1

### ISSUE THREAD

**Issue by RomainCaraty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#255]
Bonjour @sdemeyANS,

Comme vu ensemble il faut que le scénario 1 de signalement d'anomalie apparaisse sur l'IG https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_5.html avec l'exemple suivant :

►	Scenario 1 : Signalement d’une anomalie
•	Un responsable qualité souhaite signaler une anomalie sur un élément.
Exemple : signalement d’une anomalie sur la catégorie d’établissement pour un établissement spécifique

Requête : POST https://rortest.esante.gouv.fr/anomalies/Task

Body : { 
    "resourceType": "Task", 
    "focus": {
        "reference": "Organization",
        "identifier": {
            "value": "1910800002"
        }
    },
	"status": "in-progress",
	"intent": "order",
	"reasonCode": {
        "coding": [
            {
                "system": "https://mos.esante.gouv.fr/NOS/TRE_R349-ActionAnomalie/FHIR/TRE-R349-ActionAnomalie",
                "code": "COR",
                "display": "Correction"
            }
        ]
    }, 
    "code": {
        "coding": [
            {
                "system": "https://mos.esante.gouv.fr/NOS/TRE_R350-ThematiqueAnomalie/FHIR/TRE-R350-ThematiqueAnomalie",
                "code": "06",
                "display": "Exactitude"
            }
        ]
    }, 
	"description": "La catégorie d'établissement n'est pas la bonne",
    "input": [
        {
            "type": {
                "coding": [
                    {
                        "system": "https://interop.esante.gouv.fr/ig/fhir/ror/CodeSystem/input-task-ror-codesystem",
                        "code": "pathElementError"
                    }
                ]
            },
            "valueExpression": {
                "language": "text/fhirpath",
                "expression": "Organization.type.coding.where(system = 'https://mos.esante.gouv.fr/NOS/TRE_R66-CategorieEtablissement/FHIR/TRE-R66-CategorieEtablissement')"
            }
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "https://interop.esante.gouv.fr/ig/fhir/ror/CodeSystem/input-task-ror-codesystem",
                        "code": "systemRequester"
                    }
                ]
            },
            "valueString": "IHM"
        }
    ]
}

**Comment by sly-kereval** [comment]
Le narratif est mis à jour :
- maj de la description du scénario avec les valeurs de l'issue
- maj de la requete

Preview disponible : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/narratif-scenario-retour-platine-2 

Question : Pour l'élément focus, la valeur de l'élément reference ("Organization") ne correspond pas à la définition "Literal reference, Relative, internal or absolute URL" (voir [documentation](http://hl7.org/fhir/R4/references.html). Cet élément a donc été remplacé par l'élément type, qui semble mieux correspondre. Est-ce qu'il s'agit bien de l'identifier de la ressource Organization ? Car s'il s'agit de son id il faut utiliser la syntaxe suivante : `"reference": "Organization/id"`

Remarque : 
- Des éléments obligatoires de la ressource RORTask ne sont pas présents dans la requête de l'issue (businessStatus, authoredOn, lastModified), ils ont été ajoutés avec des valeurs arbitraires.

**Comment by sdemeyANS** [comment]
ok attente validation PR https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/282

**Comment by RomainCaraty** [comment]
Bonjour @sdemeyANS @sly-kereval 

La requête et le body ne change pas en 3.1.

Ce qui est affiché sur l'IG est donc correct.

Merci.
