### ISSUE TITLE
IG- Mise à jour d'anomalie : Scénario 2

### ISSUE THREAD

**Issue by RomainCaraty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#257]
Bonjour @sdemeyANS,

Comme vu ensemble il faut que le scénario 2 de mise à jour d'anomalie apparaisse sur l'IG https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_6.html avec l'exemple suivant :

►	Scenario 2 : Inactivation d’une anomalie
•	Un responsable qualité ou un système numérique décide d’inactiver une anomalie (elle a été saisie par erreur par exemple).
Exemple : Le déclarant de l’anomalie souhaite annuler l’anomalie en question.

Requête : PATCH https://rortest.esante.gouv.fr/anomalies/Task/1310

Body : { 
  "resourceType": "Bundle", 
  "type": "transaction", 
  "entry": [ 
      { 
        "resource": { 
          "resourceType": "Parameters", 
          "parameter": [ 
            { 
              "name": "operation", 
              "part": [ 
                { 
                  "name": "type", 
  "valueString": "replace" 
                }, 
                { 
  "name": "path", 
  "valueString": "Task.businessStatus" 
                }, 
                { 
  "name": "value", 
  "valueCodeableConcept": { 
  "coding": [ 
    { 
      "system": "https://mos.esante.gouv.fr/NOS/TRE_R352-StatutMetierAnomalie/FHIR/TRE-R352-StatutMetierAnomalie", 
      "code": "03", 
      "display": "Annulé" 
    } 
  ] 
                } 
              } 
            ] 
          } 
        ] 
      } 
    } 
  ] 
}

**Comment by sly-kereval** [comment]
Le narratif est mis à jour :
- maj de la description du scénario avec les valeurs de l'issue
- maj de la requête

Remarque : Dans ce scénario, on met à jour une seule ressource via une requête PATCH, le type de ressource est Parameters comme indiqué dans la [documentation](http://hl7.org/fhir/R4/fhirpatch.html) et non pas Bundle, les 5 premières lignes du corps de la requête ont donc été supprimées.

**Comment by sdemeyANS** [comment]
ok attente validation PR https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/282
