### ISSUE TITLE
HealthcareService.notAvailable

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-repertoire-offre-ressources-sante#258]
# Description du problème
<img width="1047" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/48218773/91a5cc64-262a-4662-a495-15ef31d35c8b">

Est-ce que ça serait plus simple d'utiliser une seule slice ?

**Comment by sdemeyANS** [comment]
désolé pour ce retour tardif. Traité en 0.2.0 
https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/compare/0.1.1...0.2.0#diff-0dba3977f59348bfb047d3ea92f7282d03e9819becd7c58df612f21f9b029311R150
