### ISSUE TITLE
[RC] extension au niveau de Location.status

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-repertoire-offre-ressources-sante#260]
Il aurait été préférable de mettre cette extension au niveau de Location.status, les clients risquent de nous le reprocher..
Mais peut être trop pénible pour changer aujourd'hui ?

_Originally posted by @nriss in https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/151#issuecomment-1864248337_

**Comment by sdemeyANS** [comment]
- [ ] test modif extension
- [ ] impact dev ?

**Comment by sly-kereval** [comment]
Est-ce que l'élément [operationalStatut](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-location-definitions.html#Location.operationalStatus) ne pourrait pas convenir à la place de l'extension ?

**Comment by nriss** [comment]
> Est-ce que l'élément [operationalStatut](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-location-definitions.html#Location.operationalStatus) ne pourrait pas convenir à la place de l'extension ?

Très bien vu!

**Comment by sly-kereval** [comment]
Preview en utilisant operationalStatus : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/260-location-status/StructureDefinition-ror-location.html

Impact dev : utilisation de l'élément natif operationalStatus et suppression de l'extension RORLocationStatus

**Comment by nriss** [comment]
@jcserafini à noter que plus tard, il y aura probablement des retours consommateurs qui diront que ce qu'on a fait n'est pas standard. De plus, plus on attend, plus il y aura de consommateurs, et donc plus la modification sera difficile à mettre en place.

Des évolutions non - rétrocompatibles seront inévitables à mon sens

**Comment by paulineheurtebise** [comment]
Atelier 14/02 : sera pris en compte dans de futures évolutions. 
A planifier
