### ISSUE TITLE
[RC]Intégrer MS dans les éléments differential + autres ?

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-repertoire-offre-ressources-sante#264]
# Description du problème
Besoin de distinguer les éléments nécessaire dans l'implémentation pour les consommateurs

# Fichier•s concerné•s
les profils ROR

# Solution proposée

- [ ] Ajouter MS sur les élements de differential.
- [ ] Besoin de valider les éléments non profilés dans la ressource mais qui doivent être implémenté dans le cadre du ROR

**Comment by sdemeyANS** [comment]
@jcserafini et @LudivineLacour 
suite à notre échange :)
j'aurai donc besoin d'aide pour la tache :
 

- [ ] Besoin de valider les éléments non profilés dans la ressource mais qui doivent être implémenté dans le cadre du ROR

**Comment by sdemeyANS** [comment]
doublon https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/268

**Comment by LudivineLacour** [comment]
@sdemeyANS je pense que tu peux te baser sur le mapping FHIR pour identifier les éléments non profilés implémentés par le ROR. OK pour faire une review lorsque une preview sera disponible
