### ISSUE TITLE
[RC] ror-location-equipment-limit

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-repertoire-offre-ressources-sante#266]
# Description du problème
Une extension complexe pour l’équipement a été créée via l'issue #73 mais l'élément [ror-location-equipment-limit](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-location-definitions.html#diff_Location.extension:ror-location-equipment-limit) n'a pas été retiré de la ressource Location

![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/122790741/2f855754-401f-42bf-9511-d3015ea6e370)

# Fichier•s concerné•s
[Location](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-location.html)

# Solution proposée
Retiré l'extension  [ror-location-equipment-limit](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-location-definitions.html#diff_Location.extension:ror-location-equipment-limit) de Location

Impact dev à prévoir ?

**Comment by sdemeyANS** [comment]
oui il faut la retirée
@jcserafini est ce qu'il y a un impact dev ?

**Comment by sdemeyANS** [comment]
si ok on peut l'inclure en 0.2.0

**Comment by jcserafini** [comment]
OK pour moi

**Comment by sly-kereval** [comment]
L'extension [ror-location-equipment-limit](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-location-equipment-limit.html) a été retirée de Location (elle se trouve dans l'extension [ror-location-equipment](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-location-equipment.html)).
