### ISSUE TITLE
Ajout critère recherche ID Nat PS + scénario

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#272]
# Description du problème
Pour afficher les offres accessibles par un professionnel de santé dans l'IHM du ROR national, nous souhaiterions rajouter le critère identifier sur la ressource practitioner.
Le scénario serait de ramener toutes les offres du pro avec un ID Nat PS donné.
Ce scénario et ce critère serait utile pour le serveur, et on propose de le rendre également accessible coté consommateur qu'en pense tu @PhilippeC-ANS ?

**Comment by PhilippeC-ANS** [comment]
Hello,
OK pour moi. Il me semble même que c'est un incontournable si l'on veut permettre une saisie déportée à l'avenir.

**Comment by sdemeyANS** [comment]
Bonjour,
Le critère est natif FHIR https://hl7.org/fhir/R4/practitioner.html#search

Pour l'ajout du scenario vous voulez l'ajouter ici ? https://interop.esante.gouv.fr/ig/fhir/ror/specifications_techniques_3.html
Dans quelle version cible?

**Comment by jcserafini** [comment]
@sdemeyANS On a développé le critère de recherche en 3.1, mais on a utilisé la syntaxe 
Practitioner.identifier
Comme tous les critères de recherche sur les autres ressources sont en minuscule on suppose qu'il faut faire practitioner.identifier plutot non ?
Si oui on pourra le prendre qu'en 3.2

**Comment by sdemeyANS** [comment]
@mlr-kereval pouvez-vous proposer le scenario svp ?
A noter que le sp identifier est déjà ajouté dans la branche en cours sd-update-draft-ror-31 narratif et CS

**Comment by sdemeyANS** [comment]
@Mathieu-Rousseau est ce que l'on peut le mettre dans https://interop.esante.gouv.fr/ig/fhir/ror/specifications_techniques_3.html et dans la 3.1 puisque le SP a été traité ? cf issue #288

**Comment by sly-kereval** [comment]
Proposition d'ajout de scénario : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/272-ajout-scenario-id-nat-ps/ig/specifications_techniques_3.html#sc%C3%A9nario-13-recherche-de-loffre-dun-professionnel

**Comment by sdemeyANS** [comment]
> Proposition d'ajout de scénario : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/272-ajout-scenario-id-nat-ps/ig/specifications_techniques_3.html#sc%C3%A9nario-13-recherche-de-loffre-dun-professionnel

@mathieu-decarvalho et @Mathieu-Rousseau est-ce que la propostion convient et est ce qu'on l'intègre dans la version de l'IG pour ROR 3.2 ?

**Comment by sdemeyANS** [comment]
ok pour le scenario en draft
