### ISSUE TITLE
Cardinalité Organization.address

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-repertoire-offre-ressources-sante#274]
# Description du problème

Dans la ressource FHIR [Organization](http://hl7.org/fhir/R4/organization.html) ainsi que dans le profil [FrOrganization](https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783616), la cardinalité de l'élément address est 0..*. Cette cardinalité n'a pas été contrainte dans le profil [ROROrganization](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-organization.html) alors dans le ME ROR la cardinalité de l'élément EJ/adressEJ est 0..1. 

# Fichier•s concerné•s

[ROROrganization.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/profiles/ROROrganization.fsh)

# Solution proposée

Est-ce qu'il faut contraindre l'élément Organization.address à 0..1 dans le profil ROROrganization ? 
Si oui, impact dev à prévoir ?

**Comment by sly-kereval** [comment]
@jcserafini quel est l'impact dev ?

**Comment by PhilippeC-ANS** [comment]
Dans le modèle d'exposition, la cardinalité lieu de l'EG est 0..1
Il n'est pas prévu de gérer plusieurs adresses directement rattachées à l'EG.
(Par contre, une EG peut porter des offres opérationnelles situées à des adresses différentes, mais il ne me semble pas que cela impacte la cardinalité de Organization)

**Comment by jcserafini** [comment]
@sdemeyANS @PhilippeC-ANS La cardinalité dans le modele du ROR est bien 0..1 également. Pas d'impact

**Comment by sly-kereval** [comment]
Cardinalité corrigée : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/274-cardinalite-organization-address/StructureDefinition-ror-organization.html
