### ISSUE TITLE
Recherche union implémentée uniquement avec filter

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-repertoire-offre-ressources-sante#275]
# Description du problème

Dans l'issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/234#issuecomment-1878279036, il est indiqué que la recherche d'une union de résultats (élément = valeurA ou valeurB) est implémentée uniquement avec _filter et non pas avec une virgule comme indiqué [ici](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/234#issuecomment-1878279036). 

Les scénarios suivants utilisent cette syntaxe : 
- Consultation des données capacitaires : Scénario 3 --> Modifié dans l'issue #234 
- Consultation des données capacitaires : Scénario 1bis et 5
- Recherche d'offre sur critères principaux : Scénarios 2, 9 et 12 

# Fichier•s concerné•s

[specifications_techniques_1.md](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/pagecontent/specifications_techniques_1.md)
[specifications_techniques_3.md](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/pagecontent/specifications_techniques_3.md)

# Solution proposée

Modifier les requêtes avec la syntaxe implémentée.

**Comment by sly-kereval** [comment]
Les exemples de requêtes des scénarios concernés ont été modifiés avec la syntaxe implémentée (_filter).

**Comment by sly-kereval** [comment]
_filter a été ajouté dans les tableaux de SP pour chaque ressource

**Comment by paulineheurtebise** [comment]
Atelier 14/02 : tag draft sur le scenario 12
