### ISSUE TITLE
Erreur FHIR sur une Location avec limite d'équipement

### ISSUE THREAD

**Issue by hwn-atos** [ansforge/IG-fhir-repertoire-offre-ressources-sante#279]
# Description du problème
Notre validateur FHIR remonte une erreur pour une Location qui possède un équipement avec une limite.
L'extension ror-location-equipment-limit utilisée est bien celle qui est imbriquée dans l'extension ror-location-equipment (cf. #266).
Version IG : 0.2.0

L'erreur est la suivante : 
`
The modifier extension https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-location-equipment-limit is not allowed to be used at this point (allowed = x:https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-location-equipment; this element is [Location.extension, Extension])
`

# Fichier•s concerné•s
[RORLocationEquipmentLimit.fsh](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/extensions/RORLocationEquipmentLimit.fsh)
En particulier, les lignes suivantes:
```
* ^context.type = #extension
* ^context.expression = "https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-location-equipment"
```

# Solution proposée
```
* ^context.type = #element
* ^context.expression = "Location.extension"
```

**Comment by sly-kereval** [comment]
La correction proposée a été effectuée.
