### ISSUE TITLE
Scénario manquant : Modification des données capacitaires

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#283]
# Description du problème
Il manque un scénario dans l'IG ici: 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_10.html

Il faudrait pouvoir modifier les données capacitaires. Il s'agit du scénario présenté aux bed managers et je ne le retrouve pas dans cette page.

# Fichier•s concerné•s

# Solution proposée

**Comment by sdemeyANS** [comment]
Il n'avait pas été demandé encore il me semble
On peut l'ajouter
@paulineheurtebise et @sly-kereval cf support de l'atelier bedmanagement transmis par email.
Scenario à mettre en draft.
Cible version 0.2.1

**Comment by paulineheurtebise** [comment]
Réunion 25/01/24 : 
exemple choisi : avant Location avec 2 capacités et patch en renvoyant une Location avec 3 capacités. 
insérer une image avant / après.
ajouter préconisation de renvoyer à 0 plutot que de supprimer (= ne pas renvoyer)
