### ISSUE TITLE
Territorial division - erreur de validation 

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#29]
Bonjour,
Lorsqu'on passe nos ressources healthcare service au validate à partir des ressources de conformité actuelles, on obtient l'erreur suivante concernant la donnée territorial division:
_The modifier extension https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-territorial-division is not allowed to be used at this point (allowed = e:Organization; this element is [Bundle.entry.resource.ofType(HealthcareService), BackboneElement.resource, HealthcareService])_
Il semble que c'est la même erreur qu'on a eu avec la creation date.

**Comment by sly-kereval** [comment]
Bonjour, 
Normalement cette erreur a été corrigée en même que celle concernant meta-creation-date (#24), @jcserafini pouvez-vous nous le confirmer ?

**Comment by sdemeyANS** [comment]
pour vérifier le plus simple est de passer par la preview peut-être https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/

**Comment by sdemeyANS** [comment]
@jcserafini ok pour toi ?

**Comment by sdemeyANS** [comment]
@loic-brtd  merci pour votre réponse :)
