### ISSUE TITLE
Erreur FHIR sur une Organization avec un lieu dit (precinct)

### ISSUE THREAD

**Issue by LoickZoty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#291]
# Description du problème
Notre validateur FHIR remonte une erreur pour une Organization qui possède une adresse avec un lieu dit (precinct).
L'extension precinct utilisée est bien celle qui est dans address.line

# Fichier•s concerné•s
Le precinct est une extension HL7 : https://hl7.org/fhir/R4/extension-iso21090-adxp-precinct.json.html qui a pour contexte
`"context" : [{
    "type" : "element",
    "expression" : "Address"
  }],`

Contrairement aux extensions voisines tel que "postalBox" : https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/80727/~json qui a pour contexte
`"context":  [
        {
            "type": "element",
            "expression": "Address.line"
        }
    ],`

# Solution proposée
Une solution serait d'avoir sa propre extension "precinct" en modifiant le contexte pour
`"context":  [
        {
            "type": "element",
            "expression": "Address.line"
        }
    ],`

**Comment by nriss** [comment]
Issue associée : https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/86

**Comment by paulineheurtebise** [comment]
1. A savoir que la problématique sera aussi applicable à l'Annuaire :) 

1. Je trouve ca dommage de devoir sortir l'extension de line, car c'est vraiment une des composantes des lignes de l'adresse. Mais je n'ai pas de contre proposition pour régler le problème

1. Je suppose également que sortir l'extension a des impacts dev ? @jcserafini 

1. J'ai vérifié les autres extensions, pas de soucis elle s'applique bien à Address.line

**Comment by nriss** [comment]
Je commence à remettre en question l'usage de cette extension : https://fr.wikipedia.org/wiki/Precinct

L'impact serait peut être moindre de créer une extension custom sur address.line ?

**Comment by paulineheurtebise** [comment]
PI l'issue ou nous avions identifié precinct : #86

**Comment by sdemeyANS** [comment]
@jcserafini et @sdemeyANS : 

- [ ] choisir l'option à mettre en œuvre

**Comment by sdemeyANS** [comment]
Ok on fait l'extension

**Comment by nriss** [comment]
Je m'en occupe côté annuaire, publication le 16 février, comme ça vous pouvez hériter directement de l'extension crée si possible :)

**Comment by sdemeyANS** [comment]
@sly-kereval et @paulineheurtebise pouvez faire la modification demandée ? merci

- [ ] créer l'extension

**Comment by sdemeyANS** [comment]
> Je m'en occupe côté annuaire, publication le 16 février, comme ça vous pouvez hériter directement de l'extension créée si possible :)
> 
> [EDIT] PR associée : [ansforge/IG-fhir-annuaire#165](https://github.com/ansforge/IG-fhir-annuaire/pull/165)

pas sûr que nous pourrons hériter dans un premier temps pour une question de timing ;)

**Comment by sly-kereval** [comment]
Extension créée, voici la preview : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/291-erreur-organization-lieu-dit-precinct/

Remarque : Nous avons remarqué que la cardinalité des éléments streetNameBase (libelleVoie) et lieuDit de address.line étaient différentes entre les ressources Organization et Location, elles ont été corrigées en cohérence avec le ME.
