### ISSUE TITLE
Erreur de cardinalité sur Practitionner - Civilité Personne Physique

### ISSUE THREAD

**Issue by LudivineLacour** [ansforge/IG-fhir-repertoire-offre-ressources-sante#295]
# Description du problème

Dans l'IG, la cardinalité du prefix sur l'attribut name de la ressource Practitioner, qui référence la Civilite d'une personne physique, indique une cardinalité à 0...* alors que le modèle d'exposition prévoit une cardinalité à 0..1

Ci-dessous un extrait du modèle d'exposition
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/25037491/152ad999-f824-4608-9c6b-2b1c9db71ef1)

Ci-dessous un extrait de l'IG en version 0.2.0
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/25037491/b94ed8b6-8190-4e10-9d5a-caa402318a89)

# Fichier•s concerné•s

https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-practitioner.html

# Solution proposée

Modifier la cardinalité conformément au modèle d'exposition

**Comment by sly-kereval** [comment]
Merci pour cette remarque.

C'est corrigé, voici la preview  : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/295-erreur-cardinalite-practitionner-civilité/StructureDefinition-ror-practitioner.html

**Comment by sdemeyANS** [comment]
@jcserafini pour information. Pas d'impact dev ce changement ?

**Comment by jcserafini** [comment]
@sdemeyANS Notre modèle de donnée ne permet pas 0..* mais bien 0..1.
Pas d'impact chez nous
