### ISSUE TITLE
Location : erreur de validation sur l'extension geolocation

### ISSUE THREAD

**Issue by loic-brtd** [ansforge/IG-fhir-repertoire-offre-ressources-sante#30]
Bonjour,

Prenons cette ressource FHIR qui respecte au mieux la Structure Definition fournie :
```json
{
    "resourceType": "Location",
    "id": "103",
    "meta": {
        "lastUpdated": "2023-03-31T16:48:04.000+00:00",
        "tag": [
            {
                "system": "https://mos.esante.gouv.fr/NOS/TRE_R30-RegionOM/FHIR/TRE-R30-RegionOM",
                "code": "52"
            }
        ]
    },
    "status": "active",
    "name": "Consultation kinésithérapie",
    "address": {
        "line": [
            "14 BIS R GEORGES CLEMENCEAU",
            "85140 Les Essarts"
        ],
        "_line": [
            {
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber",
                        "valueString": "14"
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-buildingNumberSuffix",
                        "valueString": "BIS"
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameBase",
                        "valueString": "R GEORGES CLEMENCEAU"
                    }
                ]
            },
            null
        ],
        "city": "Les Essarts",
        "postalCode": "85140"
    },
    "position": {
        "extension": [
            {
                "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                "extension": [
                    {
                        "url": "latitude",
                        "valueDecimal": 49.133333
                    },
                    {
                        "url": "longitude",
                        "valueDecimal": 6.166667
                    },
                    {
                        "url": "geodicSystem",
                        "valueString": "WGS84"
                    },
                    {
                        "url": "reliablePosition",
                        "valueBoolean": false
                    }
                ]
            }
        ],
        "longitude": 6.166667,
        "latitude": 49.133333
    }
}
```
Le validateur indique : 
> The modifier extension http://hl7.org/fhir/StructureDefinition/geolocation is not allowed to be used at this point (allowed = e:Address; this element is [Location.position, BackboneElement]).

En effet, la [documentation de cette extension](http://hl7.org/fhir/R4/extension-geolocation.html) native FHIR indique : 
> Context of Use: Use on Element ID Address.

Pour information, si j'utilise l'URL "https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-location-geolocation" à la place, le validateur m'indique :
> Value is 'https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-location-geolocation' but must be 'http://hl7.org/fhir/StructureDefinition/geolocation'

***Loïc BERTRAND**
loic.bertrand@atos.net
Ingénieur d’études et développement
Atos France - Département Est - Metz*

PS : Il me semble que le terme pour "système géodésique" en anglais est "geodetic system" au lieu de "geodic system".

**Comment by nriss** [comment]
@Kereval Pourquoi est-ce qu'on a fait ça si on a déjà longitude - latitude ? 

Voir avec le ror si le système géodésique est uniquement WGS84, supprimer l'usage de l'extension, et créer une extension booléenne "reliablePosition"

**Comment by sly-kereval** [comment]
Les attributs longitude et latitude sont bien mappés sur Location.position (.latitude et .longitude). 
L'extension sur geolocation permet de mapper les attributs systemeGeodesique et coordonneesFiables de la classe CoordonneeGeographique (utilisée dans la classe Lieu) du modèle d'exposition.

**Comment by nriss** [comment]
@sly-kereval FHIR impose que les données de Location.position soient en WGS84, ce qui rend l'attribut systemeGeodesique inutile 
<img width="690" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/48218773/93bc98ec-7321-43a8-ad67-eaf47494e2eb">

De plus, c'est une mauvaise pratique de dupliquer les données (latitude et longitude).
La seule info manquante est donc coordonneesFiables, il suffit donc de remplacer l'extension ror-location-geographique par une extension créée ror-fiabilite-coordonnee

**Comment by loic-brtd** [comment]
> Pour l'équipe de développement : l'extension étant d'attribut 0..1, possibilité de la retirer le temps que l'on fasse la nouvelle release (donnée retirée temporairement à valider et notifier au ROR)

Merci pour la réponse, nous ne diffuseront pas cette extension pour le moment, en attendant la nouvelle release

**Comment by nriss** [comment]
Très bien, @jcserafini tu pourras confirmer qu'il n'y a pas de soucis qu'on supprime la notion de geodesicSystem et reliablePosition temporairement avant prochaine release ? On a besoin d'expertise fonctionnelle des données du ROR pour s'en assurer

**Comment by loic-brtd** [comment]
En complément, j'ai lu dans le document "ROR - ModèleExpositionV2.4.docx" que "le système géodésique utilisé par chaque solution ROR est le WGS84." :
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/37326143/a53f199f-8124-45cf-84f0-7bca5d50d459)

**Comment by sdemeyANS** [comment]
après on est sur ME 3.0 :) mais je crois qu'il n'y a pas de changement sur ce point entre 2.4 et 3.0

**Comment by mathieu-decarvalho** [comment]
Bonjour,

    Il n'y a pas de soucis qu'on supprime la notion de geodesicSystem et reliablePosition temporairement avant prochaine release @jcserafini ?
-> pourquoi enlever reliablePosition ? il faut juste enlever geodesicSystem, latitude et longitude de l'extension.

    Est-on sûr que ce soit WGS84 dans tous les cas @jcserafini ?
-> Oui, c'est bien du WGS84 dans les ROR.

**Comment by nriss** [comment]
Super on est aligné @mathieu-decarvalho :)
Je disais : on supprime l'extension complexe existante et on la remplace par une extension simple avec uniquement reliablePosition! On peut donc y aller @sly-kereval si c'est bon pour toi :)
