### ISSUE TITLE
Informations lieu EG absentes (fonction, statut)

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#302]
# Description du problème
Le modèle d'exposition V3.0 prévoit qu'une EG soit liée à un lieu EG pouvant contenir les attributs fonctionLieu (JDV_J198), statut (TRE_R203).
La modélisation en FHIR ne permet pas de véhiculer ces attributs pour une EG. Nous ne les diffusons pas actuellement ( elles ne sont pas obligatoires).
Est ce grave ?
@PhilippeC-ANS

**Comment by PhilippeC-ANS** [comment]
De mon point de vue, l'absence de ces 2 informations au niveau du lieu de l'EG sont sans conséquences.
* La fonction lieu est facultative et est prévue pour pouvoir différents lieux sur lesquelles pourront s'appuyer une offre opérationnelle (ex : 1 lie "hébergement", un second "plateau technique bloc opératoire", un troisième "plateau technique imagerie").
* La fermeture du lieu est prévu dans le MOS (et donc dans le ME ROR) mais l'information de fermeture d'une EG est attendue dans les attributs date de fermeture et type de fermeture, et pas via la fermeture du lieu associé à l'EG.

**Comment by sdemeyANS** [comment]
@jcserafini du coup on fait quoi pour cette issue?

**Comment by jcserafini** [comment]
@sdemeyANS @PhilippeC-ANS On fait rien ! Attention par contre il est possible qu'une personne qui vérifie le ME vs la modélisation FHIR fasse le même commentaire. Seule cette issue trace cette info.
