### ISSUE TITLE
Lien entre les attributs Activité opérationnelle et Famille d'activité opérationnelle

### ISSUE THREAD

**Issue by LudivineLacour** [ansforge/IG-fhir-repertoire-offre-ressources-sante#303]
# Description du problème
La manière dont les attributs Activité Opérationnelle et Famille d'activité opérationnelle ont été modélisé avec l'élément Specialty dans la ressource HealthcareService, laisse penser qu'il n'y a pas de lien entre les deux. Or la Famille d'activité opérationnelle est un regroupement d'activités opérationnelles. Comment faire le lien entre les deux ? 

![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/25037491/995e104c-9fdb-491a-8c3e-8bb3e411ac58)

# Fichier•s concerné•s

https://interop.esante.gouv.fr/ig/fhir/ror/0.2.0/StructureDefinition-ror-healthcareservice.html

# Solution proposée

La famille d'activité opérationnelle ne devrait-elle pas être une sous-extension de l'activité opérationnelle ?

**Comment by sdemeyANS** [comment]
Bonjour,
Il y a déjà une issue sur ce sujet il me semble https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/222

**Comment by LudivineLacour** [comment]
@PhilippeC-ANS Cette issue à un impact sur nos développements BI, ils seront réalisés sans lien entre les deux attributs. Rework à prévoir si la modélisation évolue.

**Comment by sdemeyANS** [comment]
doublon avec #222 je clos
