### ISSUE TITLE
Souci cardinalité horaires 

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#307]
# Description du problème
La cardinalité de available time est 0..1 alors que dans le ME on peut avoir plusieurs horaires.
Avec cette modélisation on ne peut instancier qu'un seul jour:

<img width="536" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/123978804/902a4b92-c895-47ab-b402-2e767c677ae2">

# Fichier•s concerné•s
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-healthcareservice.html

# Solution proposée

**Comment by paulineheurtebise** [comment]
Je pense que c'est discuté en #221

**Comment by sdemeyANS** [comment]
> Je pense que c'est discuté en #221

il me semble aussi

**Comment by sdemeyANS** [comment]
@jcserafini on ferme cette issue et on traite dans #221 si c'est bien un doublon ?

**Comment by LudivineLacour** [comment]
@sdemeyANS @paulineheurtebise  A mon sens il y a deux problèmes : 
- La cardinalité du jour (discuté en #221) : on peut avoir pour un type d'horaire des horaires différents pour chaque jour de la semaine
- La cardinalité de l'horaire même : une offre ou une situation opérationnelle peut avoir plusieurs types d'horaires différents

**Comment by LudivineLacour** [comment]
@PhilippeC-ANS Cette issue a un impact sur les développements en cours du BI (un rework est potentiellement à prévoir si les développements sont impactés)

**Comment by sdemeyANS** [comment]
Doublon => cette issue sera traitée en #221

**Comment by sdemeyANS** [comment]
voir #221
