### ISSUE TITLE
Personnalisation description availableTime HealthcareService

### ISSUE THREAD

**Issue by LudivineLacour** [ansforge/IG-fhir-repertoire-offre-ressources-sante#309]
# Description du problème

La description des attributs FHIR availableStartTime et availableEndTime sur la ressource HealthcareService ne sont pas personnalisée dans le contexte du projet ROR et n'ont pas été tagués au niveau des MS support (#269 ) ce qui laisse penser que ces attributs ne seront pas utilisés par le ROR alors qu'ils sont prévus dans le modèle d'exposition par les attributs heureDebut et heureFin permettant d'indiquer la plage horaire. 

![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/25037491/74ac432f-2e3c-46af-8d72-d740f22da3be)

Ces attributs sont bien personnalisés sur la ressource PractitionerRole qui utilise également l'élément availableTime.
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/25037491/0727ea1b-13f4-4761-b054-7ab3a7367393)

# Fichier•s concerné•s

https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-healthcareservice.html

# Solution proposée

Modifier la description des attributs availableStartTime et availableEndTime dans le contexte du projet ROR et ajouter un MS

**Comment by sdemeyANS** [comment]
c'est parce qu'ils n'ont pas été profilé et pas de définition spécifique ROR pour ces sous éléments.
A noter que l'élément AvailableTime est bien en MS. Du coup le MS portent aussi sur les "sous-éléments" à mon sens
<img width="618" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/3ff62033-1f2e-4056-90d2-a1698b4eb240">

**Comment by sdemeyANS** [comment]
mais je peux ajouter MS sur ces sous-éléments si vous voulez

**Comment by LudivineLacour** [comment]
Pourquoi ces attributs sont profilés sur PractitionerRole et pas sur HealthcareService ?

De plus, je ne crois pas que tous les sous-éléments de availableTime sont implémentés par le ROR (exemple : allDay n'est pas utilisé) donc il me semble important de bien identifier ceux qui le sont avec un MS.

**Comment by sdemeyANS** [comment]
Pas profilé parce que natif je pense.
Par contre on peut mettre la même définition sur HS et mettre MS.
Pour allDay dommage parce qu'"applicativement" cela peut être intéressant
On peut mettre allDay à 0..0 si vous voulez

**Comment by sdemeyANS** [comment]
@LudivineLacour pull request en attente de validation :) https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/311
