### ISSUE TITLE
IG-  Recherche/ Consultation des données capacitaires : Scénario 1

### ISSUE THREAD

**Issue by RomainCaraty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#313]
Bonjour @sdemeyANS,

Il faudrait faire apparaître ce scénario sur l'IG pour la V2.3 du ROR national avec les informations suivantes : 

►	Scénario 1 : Données capacitaires sur le périmètre régional
•	Un consommateur souhaite récupérer l'ensemble des données capacitaires sur le périmètre régional afin de mettre à jour son système (Exemple de ROR urgence qui souhaite afficher l'ensemble des capacités sur une carte).
Exemple : récupération des données capacitaires pour la région « 52 – Pays de la Loire »

Requête : https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/Location?_revinclude=HealthcareService:location&_tag=52

**Comment by paulineheurtebise** [comment]
14/02 : scenario à ajouter

**Comment by paulineheurtebise** [comment]
Issue fermée par la PR #267
