### ISSUE TITLE
IG- Consultation des données capacitaires : Scénario 3 bis 

### ISSUE THREAD

**Issue by RomainCaraty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#314]
Bonjour @sdemeyANS,

Il faut que le scénario 3bis de consultation des données capacitaires apparaissent sur l'IG correspondant à la version 3.1 du ROR national.

► Scénario 3 bis : Données capacitaires sur plusieurs lieux de prise en charge identifiés (liste)
• Un consommateur souhaite mettre à jour dans son système les données de capacité en lits/places de certains lieux de prise en charge (il connait les identifiants et demande à lire la liste de ces données capacitaires).
Exemple : recherche des données capacitaires des locations ayant pour identifiants 140, et 141, associées aux unités d’hospitalisation complète proposant des soins intensifs spécialisés en néphrologie et hématologie, dans la région Pays de la Loire :

Requête : https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/HealthcareService?location._id=140,141&_revinclude=HealthcareService:location

Merci.

**Comment by paulineheurtebise** [comment]
14/02 - Romain/Sylvain/Kereval : nouveau scenario, pas en draft, multi ok

**Comment by paulineheurtebise** [comment]
@RomainCaraty Dans les scénarios du capacitaire nous faisons un Get Location. 
Dans ton exemple c'est un Get HealthcareService. 
Peut - on conserver les requêtes en passant par Location ?

**Comment by RomainCaraty** [comment]
Bonjour @paulineheurtebise

Effectivement il est bien plus logique de passer par la ressource Location.

La requête serait : https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/Location?_id=140,141&_revinclude=HealthcareService:location

Mais cela n'a pas été développé en 3.1. Il faudrait donc faire apparaître ce scénario en draft.
