### ISSUE TITLE
IG- Consultation des données capacitaires : Scénario 5 bis

### ISSUE THREAD

**Issue by RomainCaraty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#315]
Bonjour @sdemeyANS,

Il faut que le scénario 5bis de consultation des données capacitaires apparaissent sur l'IG correspondant à la version 3.1 du ROR national.

► Scénario 5 : Données capacitaires d’une offre opérationnelle (liste)
• Un consommateur, ayant recherché au préalable une offre de santé correspondant à ses critères, souhaite connaitre la situation des capacités pour ces offres. Le service de recherche lui ayant renvoyé les identifiants de ces offres, il les passe en paramètre de la recherche.
Exemple : Recherche des informations capacitaires pour les locations ayant un identifiant du lieu de réalisation de l’offre connu par l’instance ROR égale à 11/339772 ou 11/347254

Requête : https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/HealthcareService?location.identifier=11/339772,11/347254&_revinclude=HealthcareService:location

**Comment by paulineheurtebise** [comment]
14/02 - Romain/Sylvain/Kereval : 2 requêtes dans le même scénario

**Comment by paulineheurtebise** [comment]
@RomainCaraty Dans les scénarios du capacitaire nous faisons un Get Location.
Dans ton exemple c'est un Get HealthcareService.
Peut - on conserver les requêtes en passant par Location ?

**Comment by RomainCaraty** [comment]
Bonjour @paulineheurtebise 

Effectivement il est bien plus logique de passer par la ressource Location.

La requête serait : https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/Location?_revinclude=HealthcareService:location&_has:HealthcareService:location:identifier=11/339772,11/347254

Mais cela n'a pas été développé en 3.1. Il faudrait donc faire apparaître ce scénario en draft.
