### ISSUE TITLE
IG- Recherche d'offre sur critères principaux : Scénario 10 bis

### ISSUE THREAD

**Issue by RomainCaraty** [ansforge/IG-fhir-repertoire-offre-ressources-sante#316]
Bonjour @sdemeyANS,

Il faudrait faire apparaître ce scénario en draft (non développé en 3.1) sur l'IG.

► Scenario 10 : Recherche d’offres sur une ville https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/2 – Code commune (liste)
• Un consommateur recherche les offres proposant une activité opérationnelle et un mode de prise en charge particuliers, sur une ville, ou un ensemble de villes (code commune).
Exemple : recherche des offres caractérisées par l’activité opérationnelle « 437 – médecine générale » et un mode de prise en charge « 032 – Consultation », sur les communes 18000 (Bourges) ou 13013 (Belcodène)

Requête : https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/HealthcareService?location.commune-cog=https://mos.esante.gouv.fr/NOS/TRE_R13-CommuneOM/FHIR/TRE-R13-CommuneOM|18000,13013&specialty=https://mos.esante.gouv.fr/NOS/TRE_R211-ActiviteOperationnelle/FHIR/TRE-R211-ActiviteOperationnelle|437&characteristic=https://mos.esante.gouv.fr/NOS/TRE_R213-ModePriseEnCharge/FHIR/TRE-R213-ModePriseEnCharge|032&_include=HealthcareService:location&_revinclude=PractitionerRole:service&_include=PractitionerRole:practitioner&_include=HealthcareService:organization&_include:iterate=Organization:partof

Merci.

**Comment by paulineheurtebise** [comment]
Réunion 15/02 : 
Traité en PR #267. 
Ajout de la requete.

**Comment by paulineheurtebise** [comment]
Issue fermée par la PR #267
