### ISSUE TITLE
BedManagement - Mise à jour du lieu de réalisation de l'offre - PATCH conditionnel

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-repertoire-offre-ressources-sante#318]
# Description du problème
Issue créée à la suite de la réunion du 14/12 ROR/INTEROP/KEREVAL

Écrire le scénario 9 - PATCH - en se basant sur l'identifiant fonctionnel (identifier) du lieu de réalisation de l'offre (Location)
=> implique d'assurer l'unicité de l'identifier sur les ressources dans le temps. 

# Fichier•s concerné•s
[Scenario 9 Remplacement de toutes les données capacitaires](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/specifications_techniques_10.html#bed-management-sc%C3%A9nario-9-remplacement-de-toutes-les-donn%C3%A9es-capacitaires-draft)

# Solution proposée
Ajout de la requête dans le scenario 9 (patch conditionnel)
+ 
Warning sur la requête : préconiser le scenario patch classique + notifier sur la maturité FHIR du scénario.

**Comment by paulineheurtebise** [comment]
Traité : requête avec proposition de Warning
Preview : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/318-bedmanagement-patch-conditionnel/ig/specifications_techniques_10.html#bed-management-sc%C3%A9nario-9-remplacement-de-toutes-les-donn%C3%A9es-capacitaires-draft

**Comment by sdemeyANS** [comment]
origine de l'issue demande du ROR point du 14/02

**Comment by sdemeyANS** [comment]
pour info @jcserafini nous avons créé l'issue suite à votre demande

**Comment by sdemeyANS** [comment]
comme indiqué dans la specs FHIR le patch conditionnel est expérimental https://hl7.org/fhir/R4/http.html#patch
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/97fff58a-9967-4e26-b447-b01713a98625)

**Comment by sdemeyANS** [comment]
scenario à mettre en draft dans IG cible 3.1 même si développé en 3.2 ou +
