### ISSUE TITLE
Problème de cardinalité pour Specialty

### ISSUE THREAD

**Issue by Mathieu-Rousseau** [ansforge/IG-fhir-repertoire-offre-ressources-sante#320]
# Description du problème
Bonjour @sdemeyANS,

On a remarqué une incohérence dans l'IG pour la cardinalité de Slices for specialty pour le PractitionerRole qui est à 1.* au lieux de 0.*

# Fichier•s concerné•s
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-practitionerrole.html
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/mappingFHIR_ROR_ME3_2024_01_10.xlsx

# Solution proposée
Corriger la cardinalité pour 0.*

**Comment by sdemeyANS** [comment]
Bonjour @Mathieu-Rousseau est ce que tu peux confirmer que cela doit être modifié pour la 3.2 et donc que cela doit être dans la  prochaine version ballot ? cf milestone https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/milestone/5

**Comment by sdemeyANS** [comment]
Pul request faite https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/321

- [ ] valider la version cible du ROR (3.1 ou 3.2) pour déterminer dans quelle version de l'IG intégrer cette correction @Mathieu-Rousseau 
- [ ] valider la PR @Mathieu-Rousseau

**Comment by sdemeyANS** [comment]
> Pul request faite #321
> 
> * [ ]  valider la version cible du ROR (3.1 ou 3.2) pour déterminer dans quelle version de l'IG intégrer cette correction @Mathieu-Rousseau
> * [ ]  valider la PR @Mathieu-Rousseau

@jcserafini et @Mathieu-Rousseau vous confirmez que cette correction ne doit/peut pas être en 3.1 ?

**Comment by jcserafini** [comment]
@sdemeyANS @Mathieu-Rousseau par construction le ROR a un modele en 0..*. On peut changer dès la 3.1

**Comment by sdemeyANS** [comment]
@Mathieu-Rousseau il te reste à valider la pR mais on pourra voir cela ensemble demain matin ;)
