### ISSUE TITLE
Implémentation de l'historisation (FHIR History) ?

### ISSUE THREAD

**Issue by flachalESEA** [ansforge/IG-fhir-repertoire-offre-ressources-sante#326]
# Description du problème
Nous avons en région un besoin métier pour le pilotage via le ROR. Il s'agirait de pouvoir suivre les mises à jours de ressources à des fins de pilotage institutionnel (ex: suivre la fréquence de mis à jour des capacités disponibles sur l'année). Si j'ai bien compris, cette historisation de données existe avec le support de l’interaction "history" : https://www.hl7.org/fhir/R4/http.html#history

Est-ce que le ROR National supporte cette interaction (je n'ai rien vu dans l'IG) et si oui, pour quelles ressources ? Si non, le besoin exprimé est plutôt fort.

# Fichier•s concerné•s

# Solution proposée

**Comment by mathieu-decarvalho** [comment]
Bonjour,
Oui, le ROR national permettra de gérer l'historique est de l'interroger via history et ce sur l'ensemble des ressources utilisées pour la description de l'offre (Organization, Location, ...).
(A ce jour, seule la dernière saisie est conservée)
Une question autour du nombre d'occurrences d'enregistrement de la ressource location sera évidement à étudier car nous ne pourrons pas conserver la totalité des mises à jour (24 fois par jour par Location en automatique).
Un système type X enregistrement sur les A derniers jours, Y enregistrements sur les B derniers mois et Z enregistrements sur les C derniers ans sera certainement utilisé.
Le stockage se fera certainement dans une BDD spécifique à cet usage et le temps de réponse sera plus long.
Nous organiserons un GT sur le sujet pour revoir tous ces éléments avec les régions.
-> Attention toutefois, comme vu lors des ateliers sur le capacitaire en lit (GT1), c'est à l'outil de pilotage consommant la donnée brut capacitaire du ROR N de la mettre en forme avec son échelle de temps.
Cette fonctionnalité sera développée en v5 ou v6 du ROR N (entre 09/2025 et 11/2026).

**Comment by flachalESEA** [comment]
Merci beaucoup pour cette réponse très précise  !
