### ISSUE TITLE
Demande d'ajout SP sur HealthcareService

### ISSUE THREAD

**Issue by Mathieu-Rousseau** [ansforge/IG-fhir-repertoire-offre-ressources-sante#336]
# Description du problème
Nous aimerions ajouter deux SP qui n'existe pas aujourd'hui sur le HS 
HealthcareService.characteristic:temporalityStopService
HealthcareService. notAvailable:closingRepoeningDate 

# Fichier•s concerné•s

# Solution proposée
Pour le premier si je ne dis pas de bêtise il faut l'ajouter à la liste des données sur lesquelles characteristic peut chercher.

**Comment by sdemeyANS** [comment]
pour le premier c'est déjà effectivement ce que le Capability statement indique 
<img width="337" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/a04f10e7-891e-4270-85f5-6d7ed5dae904">

**Comment by sdemeyANS** [comment]
@Mathieu-Rousseau c'est à faire pour quelle version cible du ROR ?

**Comment by sdemeyANS** [comment]
> Du coup pour le premier c'est déjà OK ?
Si on est conforme au Capability oui
>  J'ai l'impression qu'il manque dans la liste des SP du HS sur l'IG https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/search_param.html
Ce n'est que du narratif cette partie. Cette page à terme devrait disparaître et c'est le capability statement qui doit être utilisé.

**Comment by sdemeyANS** [comment]
> Pour le ROR il les faudrait pour la 3.2
Le temps de traitement décalera d'autant la livraison de la version 0.4.0 ballot1 pour info

**Comment by sdemeyANS** [comment]
pour le point 1 c'est assez rapide dans le narratif si je dois l'ajouter.
Pour le point 2 il faut que je regarde

**Comment by sdemeyANS** [comment]
> > Du coup pour le premier c'est déjà OK ?
> 
> Si on est conforme au Capability oui. LE SP characteristic concerne tout ce qui est dans characteristic
> 
> > J'ai l'impression qu'il manque dans la liste des SP du HS sur l'IG https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/search_param.html
> 
> Ce n'est que du narratif cette partie. Cette page à terme devrait disparaître et c'est le capability statement qui doit être utilisé.

cf issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/197

**Comment by sdemeyANS** [comment]
définir SP au niveau de la period

**Comment by sdemeyANS** [comment]
traité dans la PR https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/343
en attente de review @Mathieu-Rousseau et @mathieu-decarvalho merci :)
