### ISSUE TITLE
Expliquer comment est généré l'OI

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-repertoire-offre-ressources-sante#350]
https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/f044bce58d4a47fe5a90eb7de85c934d503be894/input/fsh/profiles/ROROrganization.fsh#L73

Le format de l'OI est : Concaténation du code INSEE région et d’un identifiant généré par le ROR régional séparé par le caractère "slash" (ex: 94/666)"

Est-il possible de l'écrire dans la description de la value de l'OI ?

**Comment by flachalESEA** [comment]
Cf. https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/186
