### ISSUE TITLE
Compléter le descriptif associé à la donnée ror-healthcareservice-sensitive-unit dans le cadre de la RGPD

### ISSUE THREAD

**Issue by Philippe-Delcroix** [ansforge/IG-fhir-repertoire-offre-ressources-sante#363]
# Description du problème
Dans le cadre de la RGPD, le praticien doit pouvoir indiquer qu'il ne souhaite pas diffuser son adresse au public

# Fichier•s concerné•s

# Solution proposée
Passer ces informations en données sensibles dans la diffusion FHIR en faisant évoluer le libellé associé à la donnée [ror-healthcareservice-sensitive-unit] pour indiquer "uniteSensible (OffreOperationnelle) : Permet de signaler que toutes les informations de description d'une offre sont confidentielles **ou que le porteur d'offre ne souhaite pas diffuser**".

**Comment by sdemeyANS** [comment]
Attente validation PR

**Comment by sdemeyANS** [comment]
@PhilippeC-ANS et @mathieu-decarvalho en attente validation

**Comment by sdemeyANS** [comment]
> @PhilippeC-ANS et @mathieu-decarvalho en attente validation

en attente de validation

**Comment by sdemeyANS** [comment]
Bonjour.
Est-ce que ce sujet est toujours d'actualité?

**Comment by Philippe-Delcroix** [comment]
Bonjour Sylvain.
Suite au retour de Philippe C., le sujet a été revu.
Nous allons faire autrement que ce qui était prévu initialement.
ce ticket peut être fermé
Merci.

**Comment by sdemeyANS** [comment]
Bonjour et Merci pour ce retour :)
