### ISSUE TITLE
SearchParameter specific-competence (characteristic ?)

### ISSUE THREAD

**Issue by loic-brtd** [ansforge/IG-fhir-repertoire-offre-ressources-sante#37]
Bonjour,

Le SearchParameter [specific-competence](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/SearchParameter-ror-sp-healthcareservice-specific-competence.html) pointe sur une URL d'extension qui n'existe pas :
> HealthcareService.extension.where(url='http://interop.esante.gouv.fr/ig/fhir/ror30/StructureDefinition/ror-healthcareservice-competence-ressource').extension(url='specificCompetence').valueCode

Ce critère de recherche ne serait-il pas couvert par le champ natif FHIR `characteristic` ?

Loïc BERTRAND
[loic.bertrand@atos.net](mailto:loic.bertrand@atos.net)
Ingénieur d’études et développement
Atos France - Département Est - Metz

**Comment by sdemeyANS** [comment]
Bonjour Loïc,

Déjà je vois une erreur dans le lien "ror30"

**Comment by nriss** [comment]
Hello,
Characteristic ne cherche pas au même endroit (HealthcareService.characteristic et pas dans l'extension), il faut mettre à jour l'URL

Pour info, il faut faire attention car tu regardes là sur la version build et pas consistante.
La version publiée et packagée est disponible ici : https://interop.esante.gouv.fr/ig/fhir/ror/

Bien à toi,
Nicolas

**Comment by sly-kereval** [comment]
Bonjour, 

En effet, il faut utiliser champ natif FHIR characteristic, le paramètre de recherche va être supprimé.

Merci de nous avoir signalé cette erreur.
