### ISSUE TITLE
Différence entre IG et production 3.2 - SP

### ISSUE THREAD

**Issue by Mathieu-Rousseau** [ansforge/IG-fhir-repertoire-offre-ressources-sante#372]
# Description du problème
Après analyse l'IG qui va être publié présente des différences avec ce qui à été développé en 3.2.

Pour HealthcareService : 

- has est OK mais sur l'IG mais n'a pas été dev, il faudrait le passer en draft
- specific-competence à été dev mais je ne le retrouve pas dans l'IG, il faudrait l'ajouter

Pour Organization : 

- content à été dev mais je ne le retrouve pas dans l'IG, il faudrait l'ajouter
- filter est OK mais sur l'IG mais n'a pas été dev, il faudrait le passer en draft
- type est OK mais sur l'IG mais n'a pas été dev, il faudrait le passer en draft
- name à été dev mais je ne le retrouve pas dans l'IG, il faudrait l'ajouter
- extension.typeActivity à été dev mais je ne le retrouve pas dans l'IG, il faudrait l'ajouter

Pour Practitioner : 
- id est en draft dans l'IG mais à bien été développé, il faudrait donc enlever la mention draft
- lastUpdated est en draft dans l'IG mais à bien été développé, il faudrait donc enlever la mention draft
- tag est en draft dans l'IG mais à bien été développé, il faudrait donc enlever la mention draft
- filter est OK mais sur l'IG mais n'a pas été dev, il faudrait le passer en draft
- identifier est OK mais sur l'IG mais n'a pas été dev, il faudrait le passer en draft

Pour PractitionerRole : 

- id est en draft dans l'IG mais à bien été développé, il faudrait donc enlever la mention draft
- lastUpdated est en draft dans l'IG mais à bien été développé, il faudrait donc enlever la mention draft
- tag est en draft dans l'IG mais à bien été développé, il faudrait donc enlever la mention draft
- filter est OK mais sur l'IG mais n'a pas été dev, il faudrait le passer en draft
- identifier est OK mais sur l'IG mais n'a pas été dev, il faudrait le passer en draft

Pour Task, Questionnaire et Location, RAS

Résultat observé dans la ressources metadata en prod 3.2

# Solution proposée

**Comment by nriss** [comment]
Il aurait été préférable de discuter en amont des travaux à prioriser. Cela permet de simplifier l'IG et de travailler uniquement sur le nécessaire et avoir le temps pour faire de la qualité. De plus, la bonne pratique aurait été d'utiliser l'IG comme un entrant, un contrat d'interface, pour aligner les dev à l'IG.

Ici, on fait le contraire : revenir sur l'IG à postériori et indiquer "draft" est une pratique étrange, en termes de qualité, je trouve ça très discutable de revenir en arrière et d'indiquer ça au sein même de l'IG.

On rend l'IG lourd, difficile à lire, avec pleins de choses pas implémentées, difficile à lire ...

**Comment by sdemeyANS** [comment]
> * specific-competence à été dev mais je ne le retrouve pas dans l'IG, il faudrait l'ajouter

concernant ce critère il ne devrait pas être en prod 3.2 cf https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/37 . Le SP à utiliser est characteristic

**Comment by sdemeyANS** [comment]
> * extension.typeActivity à été dev mais je ne le retrouve pas dans l'IG, il faudrait l'ajouter

Cette extension n'existe pas dans l'IG sauf erreur donc il ne devrait pas y avoir de SP @Mathieu-Rousseau

**Comment by sdemeyANS** [comment]
> Pour Organization :
> 
> * content à été dev mais je ne le retrouve pas dans l'IG, il faudrait l'ajouter

@Mathieu-Rousseau il est draft ici https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/search_param.html#structuredefinition-ror-organization
donc il faut enlever le draft ? et l'ajouter dans les capability statement serveur ET consommateur? ou juste serveur?

**Comment by sdemeyANS** [comment]
> Pour Organization :
> 

> * name à été dev mais je ne le retrouve pas dans l'IG, il faudrait l'ajouter
Je le vois dans l'IG de mon coté.
ici https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/CapabilityStatement-ror-serveur.html#Organization1-3
et ici https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/search_param.html#structuredefinition-ror-organization

**Comment by sdemeyANS** [comment]
@Mathieu-Rousseau en attendant tes retours sur les commentaires précédents j'ai fait la PR https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/378

**Comment by Mathieu-Rousseau** [comment]
@sdemeyANS C'est validé merci
