### ISSUE TITLE
Ajouter une JDV au SP typ 

### ISSUE THREAD

**Issue by Mathieu-Rousseau** [ansforge/IG-fhir-repertoire-offre-ressources-sante#374]
# Description du problème
Aujourd'hui le SP type pour les orgas permet de chercher sur les categorieEG via les JDV JDV_J55-CategorieEG-ROR issu de TRE_R66-CategorieEtablissement, TRE_R316-AutreCategorieEtablissement et TRE_R02-SecteurActivite.
Mais il n'existe pas de SP permettant de chercher sur type:OIType via la JDV JDV_J203-TypeOrganisationInterne-ROR/FHIR/JDV-J203-TypeOrganisationInterne-ROR.

# Fichier•s concerné•s

# Solution proposée
Il faudrait que le SP type puisse également chercher sur le type OI

**Comment by nriss** [comment]
Le search param type permet de chercher sur organization.type quel que soit la slice
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/97c67f6b-974c-4233-93a9-4418be45ef06">

**Comment by sdemeyANS** [comment]
d'accord avec @nriss.
@Mathieu-Rousseau il n'y a pas de limitation FHIR pour le SP type par rapport à ta demande.
@Mathieu-Rousseau ta demande concerne plutôt les informations dans le tableau https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/search_param.html#structuredefinition-ror-organization ?
Ces tableaux apportent surtout de l'information par rapport aux attributs du MEV3.0 et les SP à utiliser.

**Comment by Mathieu-Rousseau** [comment]
Parfait, merci.
Je confirme que ma remarque porte bien sur le tableau https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/main/ig/search_param.html#structuredefinition-ror-organization
Est ce possible dans ce tableau d'ajouter à la définition la possibilité de chercher sur un typeOI ?

**Comment by Mathieu-Rousseau** [comment]
@sdemeyANS 
Plutôt pour la 3.3 on a pas prévus de patcher ça en 3.2

**Comment by nriss** [comment]
Le search param type ne cherche pas sur tout Organization.type comme indiqué dans la spec FHIR @Mathieu-Rousseau ?

**Comment by Mathieu-Rousseau** [comment]
@nriss en 3.2 type n'est pas développé, il est en cours de dev pour la 3.3

**Comment by sdemeyANS** [comment]
> @nriss en 3.2 type n'est pas développé, il est en cours de dev pour la 3.3

d'où le fait de devoir le passer en draft dans ta demande dans l'issue ici https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/374#issuecomment-2352680871
Par contre il n'était pas identifié en draft en 3.1

**Comment by sdemeyANS** [comment]
@Mathieu-Rousseau PR https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/377 prête. J'attends ta validation ;) . merci

**Comment by Mathieu-Rousseau** [comment]
@sdemeyANS c'est tout bon pour moi j'ai validé la PR
