### ISSUE TITLE
Question concernant FHIR ROR capacitaire-Unité/EG/EJ

### ISSUE THREAD

**Issue by BenkhoEsea** [ansforge/IG-fhir-repertoire-offre-ressources-sante#375]
Bonjour, 

Cette issue correspond au mail de Jean-Dominique DUBAU datant du vendredi 6 septembre : 

"Bonjour,

Nous voulons  récupérer les données du capacitaire ainsi que les unité, EG et EJ associés.

D'après l'IG, nous sommes contraints de passer par la ressource HealthcareService pour inclure les ressources nécessaires (Location, Organization).

Les _include possibles sur HealthCareService sont bien HealthcareService:organization, HealthcareService:location, Organization:partof, PractitionerRole:practitioner  d'après la page https://interop.esante.gouv.fr/ig/fhir/ror/CapabilityStatement-ror-consommateur.html .
Pour illustrer, voici un exemple d'appel :

 https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/HealthcareService?_include=HealthcareService:location&_include=HealthcareService:organization&_include:iterate=Organization:partof&_format=json

L' Include sur Organization:partOf  ne semble pas avoir d'effet sur les résultats. Or nous pensions pouvoir récupérer l'ensemble des  ressources Organization avec ce partOf  pour éviter de faire des appels supplémentaires par identifiant.
De plus, pour la ressource Organization, la documentation sur les CapabilityStatement-ror-consommateur ne propose pas dans les include un Organization:partof afin de récupérer par exemple l'EJ d'un EG.  Cela multiplie les appels pour récupérer la chaîne complète de données nécessaire à notre besoin.

Est-ce un problème de mauvaise utilisation ou de fonctionnalités manquantes sur les WS ?
Vous remerciant par avance pour votre aide.

Cordialement,"

Merci d'avance pour votre aide,
Cordialement,

**Comment by BenkhoEsea** [comment]
Merci beaucoup pour ta réponse, visiblement le mail n'avait pas été reçu.

**Comment by sdemeyANS** [comment]
Echange par email
