### ISSUE TITLE
Définir si une ressources est active ou non

### ISSUE THREAD

**Issue by Mathieu-Rousseau** [ansforge/IG-fhir-repertoire-offre-ressources-sante#381]
# Description du problème
Lors de la 4.1 nous allons avoir besoin de déterminer si une ressource FHIR est active ou non, en regardant de mon côté je ne suis pas sur d'avoir trouvé un attribut qui permettrait de faire ça, en existe il un ? ou faut il l'ajouter ? 
Cela va concerner toutes les ressources FHIR en 4.1

**Comment by sdemeyANS** [comment]
qu'entendez vous par active ?

**Comment by sdemeyANS** [comment]
sinon dans les ressources vous pouvez trouver l'éléments 'active' comme ici https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-healthcareservice.html
ou status comme ici https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-location.html

**Comment by Mathieu-Rousseau** [comment]
> sinon dans les ressources vous pouvez trouver l'élément 'active' comme ici https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-healthcareservice.html ou status comme ici https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-location.html

En effet pour HS c'st exactement ce qui nous faudrait sur les autres ressources FHIR, vu avec Mathieu DC le status du location va suffire pour cette ressources

Il nous faudrait donc le booléen active sur Organization, Practitioner et PractitionerRole.

**Comment by sdemeyANS** [comment]
> Il nous faudrait donc le booléen active sur Organization, Practitioner et PractitionerRole.

déjà présent
https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-organization.html
https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-practitioner.html
https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-practitionerrole.html
