### ISSUE TITLE
Les _include et _revInclude ne doivent pas être définis en tant que SearchParameter dans le CapabilityStatement à priori

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-repertoire-offre-ressources-sante#386]
https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/f5c2fdba5ad601a022860879e23e031accf1d39c/input/fsh/instances/ror-serveur.fsh#L47

https://chat.fhir.org/#narrow/channel/179252-IG-creation/topic/.E2.9C.94.20R5.20CapabilityStatement.20Canonical.20URL.20does.20not.20resolve.20e.2E.2E.2E/near/314578640

Ils doivent être définis ici :
<img width="857" alt="image" src="https://github.com/user-attachments/assets/f792fbac-0a34-4cc6-9434-e6f3ea148e76">

**Comment by sdemeyANS** [comment]
dans l'exemple dans les specs fhir il me semble que c'est fait comme ça https://hl7.org/fhir/R4/capabilitystatement-base.json.html

**Comment by nriss** [comment]
C'est vraiment pas clair

**Comment by sdemeyANS** [comment]
issue fermée pour le moment
