### ISSUE TITLE
release note mai 2023

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-repertoire-offre-ressources-sante#40]
Bonjour,

Il faudrait préparer la release note pour la prochaine release de l'IG prévue d'ici fin mai

**Comment by nriss** [comment]
Pour exemple, j'ai fait ça : https://github.com/ansforge/IG-documentation/issues/6

**Comment by sly-kereval** [comment]
- Correction d'erreurs de syntaxe dans la définition du contexte des extensions : #26 et #33
- Correction du code du paramètre de recherche ror-sp-capacity-update-date : #28 
- Correction de l'URL du JDV_J18-EquipementSpecifiqueROR : #31 
- Modification de l'extension concernant les coordonnées géographiques : #35 
- Suppression du paramètre de recherche ror-sp-healthcareservice-specific-competence : #39
