### ISSUE TITLE
ajouter le mapping modele logique

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-repertoire-offre-ressources-sante#64]
exemple https://build.fhir.org/ig/hl7-eu/x-ehealth/models.html
https://github.com/hl7-eu/x-ehealth/tree/master

**Comment by sdemeyANS** [comment]
A planifier

**Comment by M-Priour** [comment]
Bonjour,
Voici la requête qui permet de préconstruire le fichier de mapping : 
select 	json_extract(Resources.json,'$.name') as resource,
		json_extract(Resources.json,'$.baseDefinition') as base,
		value as element ,
		json_extract(Resources.json,	REPLACE(fullkey,'id', 'short')) as commentaire,
		json_extract(Resources.json,	REPLACE(fullkey,'id', 'min')) as min,
		json_extract(Resources.json,	REPLACE(fullkey,'id', 'max')) as max,		
		json_extract(Resources.json,	REPLACE(fullkey,'id', 'binding.valueSet')) as Valueset,				
		json_extract(Resources.json,	REPLACE(fullkey,'id', 'type')) as type,			
		json_extract(Resources.json,	REPLACE(fullkey,'id', 'mapping')) as mapping
	     
from  Resources,  json_tree(Resources.json,"$.snapshot.element") as jtree
where Resources.type="StructureDefinition"
and json_extract(Resources.json,'$.type')!='Extension'
and (jtree.key='id'   )
[
[map-ror.xlsx](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/files/13638723/map-ror.xlsx)
](url)

**Comment by M-Priour** [comment]
Il reste ensuite un indiquer le mapping dans les SD

**Comment by sly-kereval** [comment]
Propositions : 
- Tableaux par ressources en utilisant le mapping FHIR : [exemple pour la ressource HealthcareService](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/amelioration-mapping/StructureDefinition-ror-healthcareservice-mappings.html#mappings-for-healthcareservice-du-mod%C3%A8le-exposition-ror-v3)
- Schéma fonctionnel/FHIR global et schéma par ressource en plantuml dans l'[onglet mapping](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/amelioration-mapping/mapping.html) (taille de l'affichage à revoir)
- Schéma global des ressources FHIR en [page d'accueil](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/amelioration-mapping/index.html#ressources-profil%C3%A9es)

**Comment by sdemeyANS** [comment]
> Propositions :
> 
> * Tableaux par ressources en utilisant le mapping FHIR : [exemple pour la ressource HealthcareService](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/amelioration-mapping/StructureDefinition-ror-healthcareservice-mappings.html#mappings-for-healthcareservice-du-mod%C3%A8le-exposition-ror-v3)
toujours KO pour Orga ?

**Comment by sly-kereval** [comment]
> > Propositions :
> > 
> > * Tableaux par ressources en utilisant le mapping FHIR : [exemple pour la ressource HealthcareService](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/amelioration-mapping/StructureDefinition-ror-healthcareservice-mappings.html#mappings-for-healthcareservice-du-mod%C3%A8le-exposition-ror-v3)
> >   toujours KO pour Orga ?

Oui, on a fait quelques tests, ça semble être lié à l'héritage.

**Comment by sdemeyANS** [comment]
> * Schéma fonctionnel/FHIR global et schéma par ressource en plantuml dans l'[onglet mapping](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/amelioration-mapping/mapping.html) (taille de l'affichage à revoir)
Effectivement pour l'affichage :) Pas facile à lire du coup

**Comment by M-Priour** [comment]
Bonjour,
Est-ce que la requête a été utilisée pour faire le mapping ou vérifier son exhaustivité ?
Cdlt

**Comment by paulineheurtebise** [comment]
Réunion 19/02/24
---

@nriss, @sdemeyANS, @M-Priour Proposition de synthèse de nos échanges d'hier n'hésitez pas à compléter / corriger. 

### Objectif
Automatiser/industrialiser la génération de mapping pour avoir une entrée de maintenance unique. 
Consommation du mapping sous différents formats : tableau + schéma + description dans la ressource (?)

### Piste de reflexion 1 : Entrée à partir du short [Cf Support ppt](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/files/14341061/2024.02.19.Mapping.pptx))

- Inconvénient : 
   1. Détourne l'utilisation du short - Est ce que le short à vocation à véhiculer ses éléments ?
   2. Pas de solution simple à la mise en correspondance du modèle logique – est-ce que cette étape doit être simple ? c’est justement l’étape de réflexion, dans laquelle on passe le modèle logique (ROR, Annuaire, MOS, …) dans les StructureDef.
   3. Pas facile d’exporter le concept – est-ce que ce travail a vocation a être exporté au-delà de l’ANS/InteropSanté ?

- Avantages :
   1. Uniquement les shorts dans les FSH à maintenir,
   2. Possibilité de scripter à partir des shorts pour obtenir la partie mapping des FSH
   3. transparent pour l’utilisateur puisque l’IG aura bien une partie mapping classique
 
### Piste de reflexion 2 : Entrée à partir du mapping

- Avantages :
   1. Utilise la partie mapping qui répond au besoin. 

- Inconvénient :
   1. Nécessite de maintenir les courtes définitions dans le mapping et par un script on les réinjecte dans les shorts ? 
   Sinon 2 endroits sont à maintenir dans les fsh – nous semble un inconvénient majeur

**Comment by M-Priour** [comment]
Pour ma part, je suis plutôt favorable au point 2 qui est plus adapté à notre besoin et qui est plus adapté par rapport au standard.

**Comment by nriss** [comment]
> Pour ma part, je suis plutôt favorable au point 2 qui est plus adapté à notre besoin et qui est plus adapté par rapport au standard.

D'accord également, j'ai l'impression que l'on peut se permettre des petits écarts au niveau du short avec le MOS si celui-ci évolue. 
Il faut de toute façon qu'on reste conforme au scope de l'attribut FHIR en question donc il faut que ce soit maîtrisé, l'automatisation engendre un risque d'écart

Donc plutôt option 2 sans automatisation de remplissage du short
