### ISSUE TITLE
Modélisation healthcare service sur contacts - télécommunication

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#68]
Bonjour
On a identifié un souci de modélisation sur les contacts dans Healthcare Service. Suivant le MEV3.0, un contact peut avoir 0..* Télécommunication. 
Sur le mapping les attributs de telecommunication sont directement dans Contact avec une cardinalité 1..1 ou 0..1. Cela ne permet pas d'avoir n telecom dans un contact.

**Comment by jcserafini** [comment]
PI: Nous finissons le sprint qui embarque ces modifications demain. Afin de permettre la diffusion des données conformément au MEV3 on va calquer notre publication sur ce qui est fait sur la ressource Organization. On fera un rework si nécessaire

**Comment by paulineheurtebise** [comment]
Bonjour, 
Afin de clarifier ce sujet et celui des telecoms nous proposons la synthèse suivante : 

1. Le besoin Contact et Telecom

![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/122790741/adc9c1a6-de15-4653-ae61-1d6c08c5e131)


2. Constat sur ce qui est actuellement en place 

![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/122790741/360eb64b-146a-42ab-8830-9646ab2ca548)



![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/122790741/8ba48854-35b7-4f5e-a4a0-1d9becaeef92)



3. Propositions de correction et évolutions

Proposition pour Telecom : 
-> Pour Organization slicé pour telecommunication et boiteLettreMSS 

Proposition pour Contact
-> Création de l'extension complexe en 0..*
-> Suppression RORConfidentialityLevel pour utiliser de manière systèmatique RORContactConfidentialityLevel
-> Pour le name dans RORHealthcareServiceContact modification du type string en HumanName

![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/122790741/ac96e623-8fd8-4d42-ac64-fdf08d06759a)

**Comment by nriss** [comment]
Pour la boite aux lettres MSS, pourriez-vous vous aligner à ce qui a été fait côté annuaire ?
https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-organization.html

**Comment by paulineheurtebise** [comment]
@PhilippeC-ANS que penses - tu d'aligner le type de donnée de la boiteLettreMSS à l'Annuaire ? 
Actuellement : 
- Dans le ROR boiteLettreMSS est de type BoiteLettreMSS qui ne possède que des télécommunications
- Dans l'Annuaire est de type [as-mailbox-mss](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-mailbox-mss.html) c'est à dire telecommunication + type email + métadonnée bal MSS (avec le responsable, le service, etc)

**Comment by nriss** [comment]
A noter que ces metadata sont optionnelles donc à priori pas de gros changement côté ROR ?
On pourra faire un héritage à partir des profils génériques de l'annuaire directement :)

**Comment by paulineheurtebise** [comment]
Hello, 
Comme le ROR héritera à terme des profils génériques de l'Annuaire, peut être pouvons nous avancer le travail et s'aligner sur ce point dès maintenant ? 
Ce qui évolue c'est les extensions déjà créées par l'Annuaire mais qui sont facultatives : 
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/122790741/8c4ce8ca-8a69-4bdb-9879-eff89f1e32ea)

Si la décision est prise de s'aligner à l'Annuaire, faut - il bien ajouter pour la balLettreMSS les extensions suivantes présentes actuellement dans Telecom ? 
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/122790741/c396956b-ece3-481e-86ca-14de3081dd4f)

**Comment by paulineheurtebise** [comment]
La PR #87 répond au besoin initial = "un contact peut avoir 0..* Télécommunication"

Je propose d'ouvrir une autre issue pour la discussion sur la balMSS et de fermer ce point en validant la PR. 

Est ce que ca vous convient @nriss, @jcserafini, @PhilippeC-ANS ?

**Comment by sdemeyANS** [comment]
> La PR #87 répond au besoin initial = "un contact peut avoir 0..* Télécommunication"
> 
> Je propose d'ouvrir une autre issue pour la discussion sur la balMSS et de fermer ce point en validant la PR.
> 
> Est ce que ca vous convient @nriss, @jcserafini, @PhilippeC-ANS ?

OK pour moi :)

**Comment by nriss** [comment]
Ok pour moi également :)
A mon sens tu peux hériter annuaire-ballot-2 et utiliser le datatype mss, ça ne changera pas énormément avec la vraie release je pense et le besoin devrait être ok pour le ROR!

**Comment by paulineheurtebise** [comment]
Cardinalité du contact traité et mapping modifié en conséquence. 
J'ai créé l'issue #161 pour donner suite à la discussion sur la balMSS.

**Comment by sdemeyANS** [comment]
> Bonjour, Afin de clarifier ce sujet et celui des telecoms nous proposons la synthèse suivante :
> 
> 1. Le besoin Contact et Telecom
> 
> ![image](https://private-user-images.githubusercontent.com/122790741/266560021-adc9c1a6-de15-4653-ae61-1d6c08c5e131.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzUzOTAsIm5iZiI6MTcwNjI3NTA5MCwicGF0aCI6Ii8xMjI3OTA3NDEvMjY2NTYwMDIxLWFkYzljMWE2LWRlMTUtNDY1My1hZTYxLTFkNmMwOGM1ZTEzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxMzE4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmI5MWU0OWVmZTQxNTcyNGUxNDNhZDRmNzAzYjExZTM0ZmQ5NWMyYjFhNTdmNjIyMjg0ODc1YmE4MzQzMDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.42lF4eXc0MpsCN6x9nBOKwho9TB5GTe6-eGwAkEJGAM)
> 
> 2. Constat sur ce qui est actuellement en place
> 
> ![image](https://private-user-images.githubusercontent.com/122790741/266556880-360eb64b-146a-42ab-8830-9646ab2ca548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzUzOTAsIm5iZiI6MTcwNjI3NTA5MCwicGF0aCI6Ii8xMjI3OTA3NDEvMjY2NTU2ODgwLTM2MGViNjRiLTE0NmEtNDJhYi04ODMwLTk2NDZhYjJjYTU0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxMzE4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjkzMTk2MzY5ZTgyZTAwMDMwMGQwNjU3ZTNkNzExMjdhMGVjNGJjMDkwMGE4MDAzOTNlMGY4NWM4ODUzY2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0wyujpejWjLHoE8-WznbECVYZQnuYyimx4V04vof76E)
> 
> ![image](https://private-user-images.githubusercontent.com/122790741/266556988-8ba48854-35b7-4f5e-a4a0-1d9becaeef92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzUzOTAsIm5iZiI6MTcwNjI3NTA5MCwicGF0aCI6Ii8xMjI3OTA3NDEvMjY2NTU2OTg4LThiYTQ4ODU0LTM1YjctNGY1ZS1hNGEwLTFkOWJlY2FlZWY5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxMzE4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTdkOWMyYzhlM2QyYzQ0ZDI0YzM1Y2MwOTg1ODFlNGY4YTAwNDc4ODQ4MDdjNWViMDkxNzgyNDI0YjQyZTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D10IbLQclVxk6Z7nF5kYQP6IKZTpH6hidnOZdmzOOuM)
> 
> 3. Propositions de correction et évolutions
> 
> Proposition pour Telecom : -> Pour Organization slicé pour telecommunication et boiteLettreMSS
> 
> Proposition pour Contact -> Création de l'extension complexe en 0..* -> Suppression RORConfidentialityLevel pour utiliser de manière systèmatique RORContactConfidentialityLevel -> Pour le name dans RORHealthcareServiceContact modification du type string en HumanName
> 
> ![image](https://private-user-images.githubusercontent.com/122790741/266558769-ac96e623-8fd8-4d42-ac64-fdf08d06759a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzUzOTAsIm5iZiI6MTcwNjI3NTA5MCwicGF0aCI6Ii8xMjI3OTA3NDEvMjY2NTU4NzY5LWFjOTZlNjIzLThmZDgtNGQ0Mi1hYzY0LWZkZjA4ZDA2NzU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxMzE4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjQyNzM3MTU4ZWQ1NzYxNDczZGUyNWUzODUxZGZiYzg1ZTI5NjU5ZDZkMGRiNjA1ZjUxMDdjNzdmMWI0YjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.553MwAJLs--RjxZ1Jzn45LM6M73Nw1V2BmYNdwVArP4)

Hello @paulineheurtebise. Suite à une question de @LudivineLacour, peux-tu nous dire si le tableau 1 est correct stp ?

**Comment by paulineheurtebise** [comment]
Hello, 
Oui je me suis trompée dans le tableau. 
Pour l'Organization, le telecom sert pour la balMSS et le contact a ses propres telecom. 
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/122790741/a492fce6-ffb2-4928-a806-f16406ca9b98)
