### ISSUE TITLE
Questions sur le NotAvailable du HealthcareService

### ISSUE THREAD

**Issue by hwn-atos** [ansforge/IG-fhir-repertoire-offre-ressources-sante#71]
Bonjour,

Nous avons des questions sur la modélisation du champ NotAvailable du HealthcareService.

Voilà un exemple de sortie FHIR que nous obtenons pour un HealthcareService contenant une date de fermeture et une date de réouverture prévisionnelle.

```
    "notAvailable": [
        {
            "description": "notAvailable:closingDate",
            "during": {
                "start": "2030-12-30T00:00:00+00:00"
            }
        },
        {
            "description": "notAvailable:previsionalReopeningDate",
            "during": {
                "end": "2040-11-30T00:00:00+00:00"
            }
        }
    ]
```

**Question concernant le slicing du champ `NotAvailable` :**
Comment réaliser le slicing pour différencier les deux dates ? 
Sachant :
-	Qu’un objet de type BackboneElement ne dispose pas de champ URL.
-	Que la [Structure Définition](https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-healthcareservice.html) ne spécifie pas d’URL pour les slices du champ NotAvailable (contrairement aux autres champs devant être slicés).

**Question concernant la description du champ `NotAvailable` :**
Ne disposant pas de données pouvant aller dans la description du `NotAvailable`, nous nous demandions s’il n’y a pas une coquille avec la cardinalité (1..1) de la description.
Cette dernière est-elle correcte ?

Merci d’avance pour vos retours.

Hugo,
Développeur sur le projet du ROR-National.

**Comment by nriss** [comment]
Bonjour Hugo,

merci pour ton retour !
Je vois effectivement qu'il y a une erreur, le discriminator est fixé sur "url" qui n'existe pas, il faut que l'on mette à jour la spécification pour mettre un discriminator pertinent.

https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/1ac34c0da2d5ef8cce492c29c5a9581b21daf1d1/input/fsh/profiles/RORHealthcareService.fsh#L112

Je propose de fixer l'id du champs NotAvailable avec le nom de la slice et de l'utiliser comme discriminator (closingDate, previsionalReopeningDate)

Bien à vous,
Nicolas

**Comment by nriss** [comment]
Sarah, peux-tu nous mettre en reviewer quand celle-ci est validée ?

**Comment by sly-kereval** [comment]
> > Bonjour,
> > Merci pour ta proposition Nicolas, j'ai fait une PR pour la prendre en compte.
> > Concernant le second point, la cardinalité de la description, celle-ci n'a pas été modifiée par rapport à la ressource de base FHIR et il n'est d'ailleurs pas possible de la modifiée comme indiqué ici : https://build.fhir.org/profiling.html#cardinality.
> > Sarah
> 
> le lien renvoie sur la version CI de FHIR :(

Au temps pour moi, c'est corrigé, merci !

**Comment by jcserafini** [comment]
Du coup dans description peut on mettre les éléments ci dessous ?

"Date de fermeture" pour la description de la slice [notAvailable:closingDate](https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-healthcareservice-definitions.html#HealthcareService.notAvailable:closingDate)
"Date de réouverture prévisionnelle" pour la description de la slice [notAvailable:previsionalReopeningDate](https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-healthcareservice-definitions.html#HealthcareService.notAvailable:previsionalReopeningDate)

**Comment by nriss** [comment]
@jcserafini ce qui est fait ne te convient pas ?
https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/75/files

**Comment by hwn-atos** [comment]
Bonjour @jcserafini @nriss 
Je me permet d'apporter quelques précisions, car je pense qu'il y a une petite incompréhension.

Lors de nos échanges, en première attention de correction pour le `notAvailable` on avait:
```
- notAvailable:
   - slice optionnelle "closingDate":
      - period:
         - start : date de fermeture
         - end : /
      - description obligatoire : "Date de fermeture" (proposition *1)
   - slice optionelle "previsionalReopeningDate":
      - period:
         - start : /
         - end : date de réouverture prévisionnelle 
      - description obligatoire : "Date de réouverture prévisionnelle" (proposition *1)
```
D'où le dernier commentaire de @jcserafini qui proposait (*1) des valeurs pour les descriptions obligatoires des slices.

La correction actuelle (PR #75) pour le `notAvailable` est:
```
- notAvailable:
   - slice optionnelle "closingRepoeningDate":
      - period:
         - start : date de fermeture
         - end : date de réouverture prévisionnelle
      - description obligatoire : quelle valeur doit-on renseigner ici ?
```
La PR correction corrige bien techniquement le problème de différenciation des deux dates. 
La dernière interrogation restante est :  quelle valeur doit-on renseigner pour la description obligatoire de la slice closingRepoeningDate ?

**Comment by jcserafini** [comment]
@nriss @hwn-atos il me semble que la dernière question de Hugo est en suspens non ?

**Comment by LudivineLacour** [comment]
Pouvez-vous éclaircir ce point ? Cela pose problème dans les travaux de consommation des données de l'API FHIR par le BI de l'ANS. Merci !

**Comment by nriss** [comment]
La PR #91 mentionnée ci-dessus répond à la question

<img width="1790" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/48218773/b136fd77-b7c9-4cd3-aa29-928bb07e220b">

**Comment by nriss** [comment]
Je vous laisse close l'issue @LudivineLacour  @jcserafini
