### ISSUE TITLE
Problème sur les ressources liées à l'équipement

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-repertoire-offre-ressources-sante#73]
Bonjour, 

Suite aux premiers retours sur le dernière version des spécifications, concernant le cas d'usage "Création et Mise à jour du lieu de réalisation de l’offre" et plus précisément la mise à jour d'un équipement, nous avons identifié un problème sur les ressources de conformité liées à l'équipement.
En effet, actuellement 2 extensions sur Location permettent de représenter les éléments liés à l'équipement : 
- RORLocationEquipment qui représente la classe EquipementSpecifique (type et nombre d'équipement)
- RORLocationEquipmentLimit qui représente la classe LimiteCaracteristiqueEquipement (type caractéristique et limite)
Hors l'implémentation actuelle ne permet pas de faire le lien entre l'équipement et sa/ses limite(s) puisque ces 2 extensions sont "à plat" dans la ressource Location.

Nous proposons donc de déplacer l'extension RORLocationEquipmentLimit dans l'extension RORLocationEquipment.

**Comment by nriss** [comment]
Ok pour moi ! :)

Il ne faut pas réellement déplacer l'extension mais créer une extension complexe
