### ISSUE TITLE
Attributs : Incohérence entre le fichier mapping excel et IG

### ISSUE THREAD

**Issue by isidacally** [ansforge/IG-fhir-repertoire-offre-ressources-sante#78]
Il y a des incohérences de syntaxe entre les attributs du fichier de mapping excel et l'implementation guide : 

![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/139139121/63a1a414-1a0e-48f6-990c-c550b4ada481)

Cordialement,

**Comment by sly-kereval** [comment]
Bonjour, 

Merci pour question. 

Sauf erreur de ma part, les noms que vous indiquez dans la colonne "Site web" correspondent aux paramètres de recherche et non aux attributs de ressources FHIR, ce qui explique la différence de syntaxe. 
Par exemple, pour nbCapacity, le nom de l'attribut dans l'[extension](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/StructureDefinition-ror-location-supported-capacity.html) est bien nbCapacity et un [paramètre de recherche](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/SearchParameter-ror-sp-nb-capacity.html) dont le nom est nb-capacity est associé à cet attribut. 
La liste des paramètres de recherches est également disponible [ici](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/search_param.html).

J'espère que cette explication vous aidera, n'hésitez pas à réagir sur ma réponse.

Bien à vous. 

Sarah
