### ISSUE TITLE
IG : Il manque des exemples de Bundle de réponse FHIR

### ISSUE THREAD

**Issue by isidacally** [ansforge/IG-fhir-repertoire-offre-ressources-sante#80]
Est-ce possible d'avoir quelques exemples de bundle de réponse FHIR svp ?

Merci.

Cordialement,

**Comment by sdemeyANS** [comment]
lié à l'issue #23

**Comment by sdemeyANS** [comment]
En attente de la production des exemples

**Comment by sdemeyANS** [comment]
Bonjour @isidacally nous fermons cette issue qui sera traitée dans celle-ci https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/23 
Bien à vous
