### ISSUE TITLE
Cohérence terminologies unité de prix et de mesure 

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-repertoire-offre-ressources-sante#81]
Des incohérences entre le modèle d'exposition et les ressources de conformité ont été identifiées concernant 2 nomenclatures, en effet :
- La [TRE_R247-UcumUniteMesure](https://mos.esante.gouv.fr/NOS/TRE_R247-UcumUniteMesure/TRE_R247-UcumUniteMesure.pdf) est utilisée pour l'attribut uniteMesure de la classe Mesure, mappé en FHIR sur [Quantity.code](http://hl7.org/fhir/R4/datatypes.html#quantity). Il est précisé que si l'unité peut être codée, le code doit être issu de [UCUM](https://ucum.org/), qui contient bien les valeurs de la TRE_R247.
- La [TRE_R230-Devise](https://mos.esante.gouv.fr/NOS/TRE_R230-Devise/TRE_R230-Devise.pdf) est utilisée pour l'attribut devise de la classe Montant, mappé en FHIR sur [Money.currency](http://hl7.org/fhir/R4/datatypes.html#Money). Le valueset [Currencies](http://hl7.org/fhir/R4/valueset-currencies.html) est required pour cet élement, il contient bien le seul code présent dans la TRE_R230 "EUR".
Nous conseillons donc conserver les valuesets utilisés par FHIR puisqu'ils contiennent les valeurs des TRE et de modifier le modèle d'exposition en conséquence. De plus, les nomenclatures NOS issues de terminologies externes sont vouées à disparaître.

**Comment by sdemeyANS** [comment]
ok pour moi
