### ISSUE TITLE
Ressource Organization: question sur le system des Identifiers

### ISSUE THREAD

**Issue by hwn-atos** [ansforge/IG-fhir-repertoire-offre-ressources-sante#83]
Bonjour,

Nous avons une interrogation pour la valeur que doit prendre le `system` des Identifiers de la ressource Organization.

La description de la Structure Definition indique « **The namespace for the identifier value** ».

Savez-vous à quoi cela correspond pour les Identifiers suivants : idNatStruct, numFINESS, numSIREN, numero_cabinet_RPPS, numSIRET, identifierOI, numero_cabinet_ADELI ?

Merci d’avance pour vos retours.

Hugo,
Développeur sur le projet du ROR-National.

**Comment by nriss** [comment]
Bonjour !
C'est un gros chantier que l'on est en train de mener, pour l'instant on s'oriente vers ça pour idNatStruct, finess, siren, rpps, adeli:
- https://ansforge.github.io/IG-fhir-annuaire/ig/main/StructureDefinition-as-organization.html

**Comment by sdemeyANS** [comment]
@jcserafini je pense que c'est un sujet qui doit être vu avec Philippe (+ MOS NOS ?)
Par définition, pour OI il ne doit pas y avoir de système unique défini j'imagine.

**Comment by PhilippeC-ANS** [comment]
Hello,
désolé mais je ne suis pas sûr de comprendre la question. Pour moi les systèmes à prendre en compte sont bien ceux du JDV J236 évoqué par Nicolas.

Les valeurs à utiliser pour les identifiers demandés sont :
idNatStruct 1.2.250.1.71.1.2.14 code 40
numFINESS 1.2.250.1.71.1.2.14 code 1
numSIREN 1.2.250.1.71.1.2.14 code 2
numero_cabinet_RPPS 1.2.250.1.71.1.2.14 code 4
numSIRET 1.2.250.1.71.1.2.14 code 3
numero_cabinet_ADELI 1.2.250.1.71.1.2.14 code 0
où 1.2.250.1.71.1.2.14 correspond à https://mos.esante.gouv.fr/NOS/TRE_G07-TypeIdentifiantStructure/FHIR/TRE-G07-TypeIdentifiantStructure

identifierOI 1.2.250.1.213.3.3.229 Code 42
où 1.2.250.1.213.3.3.229 correspond à https://mos.esante.gouv.fr/NOS/TRE_R345-TypeIdentifiantAutre/FHIR/TRE-R345-TypeIdentifiantAutre

**Comment by nriss** [comment]
Que pensez-vous de ça ? https://mos.esante.gouv.fr/6.html#_4d544200-4d26-4cc5-8294-c862458f60d8
@M-Priour tu as un avis ?

**Comment by nriss** [comment]
Discuté avec mael : 

on propose https://oi.esante.gouv.fr et on demande une redirection vers https://mos.esante.gouv.fr/6.html#_4d544200-4d26-4cc5-8294-c862458f60d8

@MohammedChaabaoui @mchaabaoui utilisez-vous l'organisation interne côté annuaire ?

**Comment by jcserafini** [comment]
@nriss @sdemeyANS j'ai l'impression que le souci des types d'identifiers est traité (en gros on utilise la JDV 236). 
Le sujet en fin de conversation est un autre problème non ? (les types OI).
Peut on fermer cette issue pour ne pas mélanger ? Quitte à en ouvrir une autre si nécessaire ?

**Comment by nriss** [comment]
Les différents sytems:
- idNatStruct : urn:oid:1.2.250.1.71.4.2.2
- numFINESS :  http://finess.esante.gouv.fr
- numSIREN : http://sirene.fr (en discussion, cf https://github.com/ansforge/IG-fhir-annuaire/issues/115)
- numSIRET : urn:oid:1.3.2
- identifierOI : https://oi.esante.gouv.fr/ (rajouter https://mos.esante.gouv.fr/6.html#_4d544200-4d26-4cc5-8294-c862458f60d8 dans la description du champs)

A discuter @PhilippeC-ANS :
- numero_cabinet_RPPS : Est-ce qu'il s'agit du numéro ADELI du PS ? Si oui https://annuaire.sante.fr
- numero_cabinet_ADELI  : Est-ce qu'il s'agit du numéro ADELI du PS ? Si oui https://annuaire.sante.fr
