### ISSUE TITLE
Souci modélisation EG - géolocalisation

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#94]
Certains consommateurs (santé.fr en particulier) ont besoin de consommer la géolocalisation des établissements de santé (EG).
Actuellement dans la modélisation FHIR, cette donnée n'est pas véhiculée dans l'organization mais dans la location, et nous ne lions pas la location à l'organization. 
Cette issue doit être suivie avec l'équipe métier et technico fonctionnelle ROR pour décider de la modélisation à appliquer pour permettre de diffuser les géolocalisations .

**Comment by nriss** [comment]
Les Organization peuvent avoir plusieurs Location, il faut donc effectivement que la geoloc soit dans Location.

Je propose de vérifier qu'il n'y ait pas de lien existant. Si c'est effectivement le cas, je propose de rajouter ce lien.

**Comment by sdemeyANS** [comment]
doublon avec issue #69? on peut closed 1 des 2 @jcserafini ?

**Comment by paulineheurtebise** [comment]
Le lien entre Location et Organization est bien présent pour moi. 
Dans la ressource Location, il y a la référence vers Organization : Location.managingOrganization --> Organization.

Qu'est ce qui est entendu par geolocalisation, est ce que c'est le calulatedDistance ?

**Comment by paulineheurtebise** [comment]
Atelier 06/09 : 

- N’est pas un doublon avec la #69 CalculatedDistance.
- Géolocalisation = longitude, latitude et système. 
- Besoin pour Santé.fr d’avoir une adresse de l’EG qui soit géolocalisée. 
- Vérifier si cette problématique a déjà été traitée dans un autre IG ou R5 avant d’ajouter 3 extensions dans l’Adresse de Organization.
- Ce sujet est prioritaire est doit être adressé dans la prochaine release de l’IG

**Comment by sdemeyANS** [comment]
https://build.fhir.org/ig/HL7/fhir-extensions/StructureDefinition-geolocation.html

**Comment by sdemeyANS** [comment]
Du coup que souhaitez vous faire ? remettre cette extension dans Address et supprimer ce qui a été fait dans Location ?


![Image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/36972a37-0784-4c6f-8c33-0bbd88f5207e)

**Comment by sdemeyANS** [comment]
Ce que l'on peut faire c'est mettre MS Location.managingOrganization
@jcserafini ok pour vous?

**Comment by sdemeyANS** [comment]
proposition : preview https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-add-MS-managingOrganization/StructureDefinition-ror-location.html

**Comment by jcserafini** [comment]
Bonjour, je vois un souci à lier l'organisation et la location: nos requêtes partent systématiquement de Healthcare service et notre manière de reconstituer le ME part également de HS. Du coup il faudra rajouter partout un nouveau critère pour ramener les Location des Orgas.
Autre sujet : dans la preview on voit les adresses conservées sur les orgas du coup quel serait l'intérêt ?

**Comment by sdemeyANS** [comment]
Je réouvre le sujet suite à nos échanges de ce jour

**Comment by sdemeyANS** [comment]
note: spécifier dans la definition de l'adresse d'orga qu'elle concerne aussi l'EG

**Comment by jcserafini** [comment]
Ci dessous les arguments liés aux 2 options pour gérer ce sujet.
	- Option 1 : Extension de l’adresse de l’EG dans Organization
			o Pros : 
                            - Changement simple par rapport à l’existant (on ajoute « juste » la donnée dont on a besoin)
                            - Les développements BI sont partis dans ce sens
			o Cons :
                            -  Nouvelle extension FHIR pour une donnée qu’on a déjà ailleurs
                            -  Fonctionnement différent de Healthcare service

	- Option 2 : Lier Organization et Location:
			o Pros:
                            - Lien natif existe déjà entre Organization et Location sur FHIR
                            - La géolocalisation est déjà modélisée dans Location, fonctionnement iso avec Healthcare service
- 			o Cons :
                              - Ajouter un lien dans le modèle FHIR va complexifier les requêtes pour récupérer le modèle d’exposition
                              - On va mélanger des notions dans la location (la location est aujourd'hui utilisée pour porter des notions de capacitaires , d'équipements -> ce sont des notions d'offre)

				
				
NB: Adresse est dans Organization ET dans Location

**Comment by sdemeyANS** [comment]
En attente retour et validation sur la PR #200

**Comment by PhilippeC-ANS** [comment]
Après vérification auprès de santé.fr, les coordonnées géo de l'EG seront bien utilisées, et nécessite également la présence au niveau de la géoloc de l'EG de l'information "coordonnées fiables" (iso à ce qui existe sur l'offre).
@sdemeyANS je te laisse regarder comment véhiculer cette info au niveau de la géoloc de l'EG ?

**Comment by sdemeyANS** [comment]
> Après vérification auprès de santé.fr, les coordonnées géo de l'EG seront bien utilisées, et nécessite également la présence au niveau de la géoloc de l'EG de l'information "coordonnées fiables" (iso à ce qui existe sur l'offre). @sdemeyANS je te laisse regarder comment véhiculer cette info au niveau de la géoloc de l'EG ?

coordonnées fiables = latitude / longitude ?
comme défini dans l'extension que j'ai ajouté ? https://hl7.org/fhir/R4/extension-geolocation.html

**Comment by sdemeyANS** [comment]
@PhilippeC-ANS et @jcserafini pour info réponse annuaire https://github.com/ansforge/IG-fhir-annuaire/issues/131#issuecomment-1843316618

**Comment by nriss** [comment]
> Après vérification auprès de santé.fr, les coordonnées géo de l'EG seront bien utilisées, et nécessite également la présence au niveau de la géoloc de l'EG de l'information "coordonnées fiables" (iso à ce qui existe sur l'offre). @sdemeyANS je te laisse regarder comment véhiculer cette info au niveau de la géoloc de l'EG ?

Tu as vu ce qui a été fait dans la PR #200  @PhilippeC-ANS ?
