### ISSUE TITLE
Bulk data import

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-repertoire-offre-ressources-sante#95]
La problématique de partage de beaucoup de données et des perfs est apaprue.

cf https://chat.fhir.org/#narrow/stream/179167-hapi/topic/Performance.20as.20FHIR.20server/near/379037591

Il semblerait que l'usage du bulkdata pourrait résoudre ce pb, à étudier : https://hl7.org/fhir/uv/bulkdata/export.html

A discuter avec @sdemeyANS

**Comment by nriss** [comment]
Idée : le consommateur fait sa demande au service, le service renvoie un lien qui contiendra le ndjson.
Cf : https://docs.google.com/presentation/d/14ZHmam9hwz6-SsCG1YqUIQnJ56bvSqEatebltgEVR6c/edit#slide=id.g8c17644f87_23_1062

**Comment by sdemeyANS** [comment]
Cette solution est intéressante.
Si c'est ok côté implementeur, je propose de faire un ou des nouveaux scénarios (ou modifier certains existants?) dans l'IG pour donner des exemples de requêtes afin d'obtenir des extractions "asynchrones complète" qui remontent beaucoup de résultats.
Afin de valider la solution, je pense qu'il serait intéressant de fixer ou se trouve le "nœud" qui induit le problème de performance au préalable.  @jcserafini  et @nriss qu'en pensez-vous?

**Comment by nriss** [comment]
Discussion du 29 août:
- Remplacer le scénario 1 d'export complet par le bulk data
- Le scénario 6 de mise à jour risque de poser pb si on utilise un lastUpdated très vieux (ex 1900). Proposition : ne pas contraindre l'utilisateur à faire une demande avant une certaine date, mais préciser qu'il y a un risque de TimeOut, et le cas échéant, privilégier le scénario 1.

**Comment by sdemeyANS** [comment]
pour info branche prospective en cours https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/tree/sd-bulk-data-import
preview IG https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-bulk-data-import/

**Comment by sdemeyANS** [comment]
reunion 11/09
ajouter un scenario avec _typeFilter juste region vu avec @jcserafini

**Comment by sdemeyANS** [comment]
scenario 1 mettre que $export

**Comment by sdemeyANS** [comment]
ne pas accepter le ndjson

**Comment by sdemeyANS** [comment]
> > ne pas accepter le ndjson
> 
> Comment ça ?

Retour en réunion ce jour. L'implementation en cours renvoie que du json

**Comment by sdemeyANS** [comment]
en complément The server SHALL support [Newline Delimited JSON](http://ndjson.org/), but MAY choose to support additional output formats. The server SHALL accept the full content type of application/fhir+ndjson as well as the abbreviated representations application/ndjson and ndjson.

**Comment by sdemeyANS** [comment]
> scenario 1 mettre que $export

@jcserafini mais du coup selon remonte tout même Task non ?

**Comment by sdemeyANS** [comment]
> en complément The server SHALL support [Newline Delimited JSON](http://ndjson.org/), but MAY choose to support additional output formats. The server SHALL accept the full content type of application/fhir+ndjson as well as the abbreviated representations application/ndjson and ndjson.

@jcserafini et @nriss la non utilisation de ndjson sera à rediscuter je pense au prochain point hebdo

**Comment by jcserafini** [comment]
> > scenario 1 mettre que $export
> 
> @jcserafini mais du coup selon remonte tout même Task non ?

@sdemeyANS Dans ce qu'on développe on ne remonte pas le task non. Ca ne concerne pas les mêmes catégories d'utilisateurs pour moi. 
@nriss @sdemeyANS  OK pour parler du ndjson. On n'a pas forcément de difficulté technique à faire cela. On avait arbitré/priorisé car cela représente un cout de développement et que nos utilisateurs actuels sont en ordre de marche pour consommer du json

**Comment by sdemeyANS** [comment]
> > > scenario 1 mettre que $export
> > 
> > 
> > @jcserafini mais du coup selon remonte tout même Task non ?
> 
> @sdemeyANS Dans ce qu'on développe on ne remonte pas le task non. Ca ne concerne pas les mêmes catégories 

le fait de ne pas tout remonter sans filtrer sur le type de ressources je ne suis pas sûr que cela soit conforme à l'IG https://hl7.org/fhir/uv/bulkdata/export.html du coup

**Comment by sdemeyANS** [comment]
voici le résultat de ma dernière itération 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-bulk-data-import/specifications_fonctionnelles.html#sc%C3%A9narios-1

https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-bulk-data-import/specifications_techniques_2.html#exemples-de-requ%C3%AAtes

@jcserafini n'hésite pas à partager à Mathieu et me faire des retours sur cette proposition.
Je vais faire une PR pour mettre en évidence les dernières modifs.
J'ai une question. Est-ce que l'on supprime totalement le scenario extraction complète 'synchrone" de la spec ? Je l'ai juste flaguée "deprecated pour le moment

**Comment by nriss** [comment]
Pour info, voici des slides présentées lors des devdays définissant clairement comment fonctionne le bulk : 

https://docs.google.com/presentation/d/1gWZwiIF73oV0LcqHKV0DXSJnzAR82qS9lGRDY67E1AQ/edit#slide=id.g8c17644f87_23_1157
