### ISSUE TITLE
Localisation d'une erreur : usage de fhirpath ou bien d'un code-valeur ?

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-repertoire-offre-ressources-sante#96]
FHIRPATH:
- Avantage : FHIR Compliant, potentiellement facilitant si on utiliser HTTP PATCH, seule solution permettant d'aller à l'identification de l'attribut en erreur le plus finement possible
- Inconvénient : difficulté à mettre en place pour les clients

Code:
- Avantage : potentiellement plus facile pour les users
- Inconvénient : dur à maintenir, ne permet pas de définir finement l'attribut en erreur

Possibilité intermédiaire : 
- trouver une solution de construction automatique du FHIRPATH / l'associer au mapping du ME directement dans la SD ?
- Utilisation de [l'id](https://www.hl7.org/fhir/R4/elementdefinition.html#id) de l'attribut dans les SD associé au short pour décrire l'attribut du ME concerné ?
- Utilisation du FHIRPATH si on veut rentrer en précision dans l'attribut bien spécifique

A discuter avec @sdemeyANS 

Un exemple d'IG utilisant TASK pour corriger : https://build.fhir.org/ig/HL7/fhir-patient-correction/index.html

**Comment by sdemeyANS** [comment]
Comme vu ce jour. On reste sur fhirpath et on met de côté cet issue
