### ISSUE TITLE
Determination des actes spécifiques hors cabinet

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#97]
Aujourdhui, les actes spécifiques et actes hors cabinet sont modélisés dans un slicing de speciality sur healthcare service.
On ne comprend pas comment les diffuser de manière distincte avec cette modélisation.

**Comment by sdemeyANS** [comment]
ce n'est pas  le slicing sur characteristic plutôt ?
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/52c34491-4e33-4664-92e5-3d1f42172db2)

**Comment by paulineheurtebise** [comment]
Atelier 06/09 : 
o	Même logique à appliquer que sur l’issue #34
o	Est-ce que le fait que la fin de l’id change, c’est-à-dire soit incrémenté pose un problème en FHIR ?

**Comment by nriss** [comment]
Je ne comprends pas le deuxième point @paulineheurtebise 
Attention, il me semble que deux champs ne peuvent pas avoir le même id (si champs multivalué)

**Comment by paulineheurtebise** [comment]
Effectivement Nicolas, je n'ai pas été des plus explicite et compréhensible dans mes notes. 
Depuis j'ai aussi fait des recherches pour les slices avec les id. 

Je pense que nous sommes exactement dans le même cas que l'issue #34, à faire un slice sur l'id pour ces 2 éléments dans le slice sur l'url de characteristic. 
Le fait que l'élément soit multivalué ne pose pas de problème je pense parce que l'id est l'id de la sous liste/tableau et chaque élément de ce slice aura un id[0], id[1], etc non ? 

J'espère que c'est compréhensible.

**Comment by nriss** [comment]
Oui je vois les choses comme ça également @paulineheurtebise  :)
Ca serait plutôt element[0].id et element[1].id étant donné que id n'est pas multivalué mais on est d'accord :)

**Comment by jcserafini** [comment]
Bonjour
Pas sur de comprendre du coup ça donnerait quoi en sortie ?

**Comment by sdemeyANS** [comment]
pour info @jcserafini solution proposée
preview preview https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/97-determination-des-actes-sp%C3%A9cifiques-hors-cabinet/StructureDefinition-ror-healthcareservice.html
cf PR https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/132

**Comment by paulineheurtebise** [comment]
Synthèse à ce jour : 

- Problématique : les attributs acteSpecifique et acteHorsCabinet sont des attributs codés qui utilisent le même JDV (et donc les mêmes TRE).
Nous avons mappé en FHIR c'est deux éléments (et d'autres) sur HealthcareService.characteristic. 
Nous avons slicé cet attribut avec le discriminateur sur l'url des CodeSystem (TRE)
Le discriminant ne fonctionne donc pas pour les attributs acteSpecifique et acteHorsCabinet. 

- Recherche d'un discriminateur : Nous avons réalisé plusieurs essais pour trouver un discriminateurs qui n'a pas abouti : 
   - Id : le slice est multivalué, l'id doit etre unique donc ne peut pas 
   - Path : meme logique que id 
   - Url de Code System : n'est pas discriminant dans ce cas car meme JDV
   - Recherche d'autres discriminants non trouvés

-  Question posée sur [Zulip](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Slicing.20search.20for.20a.20discriminator)


-  Piste de réflexion : 
   - Est-ce que c'est pertinent de mapper ces attributs sur characteristic ou plutôt sur specialty ? (proposition de @nriss  ) 
--> en mappant sur specialty la problématique du slice reste la même
   - Est-ce que finalement c'est pas le même attribut qui aurait un type fixé spécifique/hors cabinet ? 
--> Si on envisage le type, ca pourrait etre un discriminant, tout comme le type pour les identifiants.

**Comment by nriss** [comment]
Merci pour ton compte rendu très clair Pauline!
Pour le type fixé, tu verrais une extension fixée et obligatoire qui indique si c'est spécifique ou hors cabinet, c'est bien ça ?

Je ne vois pas d'autres solutions. Je pense que dans tous les cas, il faut faire l'étude de voir si c'est dans characteristic plutôt que specialty

**Comment by sdemeyANS** [comment]
> Synthèse à ce jour :
> 
> * Problématique : les attributs acteSpecifique et acteHorsCabinet sont des attributs codés qui utilisent le même JDV (et donc les mêmes TRE).
>   Nous avons mappé en FHIR c'est deux éléments (et d'autres) sur HealthcareService.characteristic.
>   Nous avons slicé cet attribut avec le discriminateur sur l'url des CodeSystem (TRE)
>   Le discriminant ne fonctionne donc pas pour les attributs acteSpecifique et acteHorsCabinet.
> * Recherche d'un discriminateur : Nous avons réalisé plusieurs essais pour trouver un discriminateurs qui n'a pas abouti :
>   
>   * Id : le slice est multivalué, l'id doit etre unique donc ne peut pas
>   * Path : meme logique que id
>   * Url de Code System : n'est pas discriminant dans ce cas car meme JDV
>   * Recherche d'autres discriminants non trouvés
> * Question posée sur [Zulip](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Slicing.20search.20for.20a.20discriminator)
> * Piste de réflexion :
>   
>   * Est-ce que c'est pertinent de mapper ces attributs sur characteristic ou plutôt sur specialty ? (proposition de @nriss  )
>     --> en mappant sur specialty la problématique du slice reste la même
>   * Est-ce que finalement c'est pas le même attribut qui aurait un type fixé spécifique/hors cabinet ?
>     --> Si on envisage le type, ca pourrait etre un discriminant, tout comme le type pour les identifiants.

@PhilippeC-ANS et @jcserafini qu'en pensez-vous ?

**Comment by paulineheurtebise** [comment]
>Pour le type fixé, tu verrais une extension fixée et obligatoire qui indique si c'est spécifique ou hors cabinet, c'est bien ça ?

Exact !

**Comment by PhilippeC-ANS** [comment]
La notion de "type fixé" je ne suis pas sûr de comprendre ce que cela signifie.
Il faut que l'offre exposée puisse comporter 0 à n actes spécifiques et 0 à n actes spécifiques hors cabinet.

La différenciation ne peut pas se faire sur la valeur de l'AS : (par exemple) la pose de holter implantable (AS1246) est un acte spécifique pour une unité hospitalière de cardiologie, et un acte spécifique hors cabinet pour un cabinet de ville de cardiologie.

=> le "type fixé" ne peut donc pas être lié à la valeur de nomenclature, mais déterminé par la saisie de l'offre par le porteur d'offre.

La proposition me convient si elle est compatible avec cela, et que l'on peut expliquer dans l'IG à nos consommateurs comment interpréter l'information qu'ils trouvent dans le ROR.

**Comment by sdemeyANS** [comment]
> > Pour le type fixé, tu verrais une extension fixée et obligatoire qui indique si c'est spécifique ou hors cabinet, c'est bien ça ?
> 
> Exact !

OK pour moi :)

**Comment by sdemeyANS** [comment]
donc si je résume: 

- [x] choix type 'fixé' pour discrimer

- [ ] choix slice charasterisic ou specialty pour le mapping

si on reponte cela dans specialty il faudra se poser la question sur d'autres charasterisitc je pense comme https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-healthcareservice-definitions.html#diff_HealthcareService.characteristic:takingCareSpeciality
Du coup cela modifie le mapping, la SD et demandera du rework en dev @jcserafini

**Comment by PhilippeC-ANS** [comment]
Par rapport à notre utilisation de ces attributs il me semble plus logique que cela soit dans characteristic.
Dans tous les cas, il est logique de véhiculer les 2 (actes spécifiques et actes spécifiques hors cabinet) avec le même attribut => les traiter tous les 2 en speciality ne résout pas notre problème, et il ne me semble pas cohérent d'en véhiculer un via characteristic et l'autre via speciality.

De ce que j'en comprends le type "fixé" peut répondre à notre besoin ; je m'interroge par contre sur son aspect obligatoire.
Cela sous-entend il qu'il faudra indiquer un type pour toutes les "characteristic" ou seulement pour AS et AS hors cabinet ?

**Comment by sly-kereval** [comment]
Si besoin, la preview est disponible ici : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/97-determination-des-actes-sp%C3%A9cifiques-hors-cabinet/StructureDefinition-ror-healthcareservice.html

**Comment by jcserafini** [comment]
ça donnerait ça instancié ? 	
{
                        "coding": [
                            {
                                "system": "https://mos.esante.gouv.fr/NOS/TRE_R210-ActeSpecifique/FHIR/TRE-R210-ActeSpecifique",
                                "code": "0884",
                                "display": "Animation socio-culturelle"
                            }
                        ],
						"code": "outsideOfficeAct"
                    },

**Comment by sly-kereval** [comment]
@jcserafini, c'est l'idée, juste il manque juste la bonne syntaxe pour l'extension, voilà ce que ça donnerait : 

```json
{
  "coding": [
    {
      "system": "https://mos.esante.gouv.fr/NOS/TRE_R210-ActeSpecifique/FHIR/TRE-R210-ActeSpecifique",
      "code": "0884",
      "display": "Animation socio-culturelle"
    }
  ],
  "extension": [
    {
      "url": "https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-act-type",
      "valueCode": "outsideOfficeAct"
    }
  ]
}
```json
