### ISSUE TITLE
Les identifiers ne précisent pas le system associé

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#98]
Dans l'IG , les identifiers des différentes ressources ne précisent pas les systems qui référencent les types d'identifiants (https://mos.esante.gouv.fr/NOS/JDV_J236-TypeIdentifiant-ROR)
D'un point de vue consommateur cela peut rendre l'interprétation compliquée.

**Comment by nriss** [comment]
Cf https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/83, utiliser le system comme discriminant devrait être suffisant

**Comment by jcserafini** [comment]
Justement c'est ce qui nous pose souci, dans l'IG on ne voit pas la notion de system pour les type d'identifiant. On va les rajouter

**Comment by sdemeyANS** [comment]
je propose du coup de clore cet issue et de la traiter dans #83
