### ISSUE TITLE
Préciser le type d'identifier dans une recherche

### ISSUE THREAD

**Issue by jcserafini** [ansforge/IG-fhir-repertoire-offre-ressources-sante#99]
Pour certaines recherches par identifier on souhaiterait pouvoir préciser les type d'identifier à appliquer.
Peut on utiliser le modifier of-type proposé dans HL7 ?

**Comment by paulineheurtebise** [comment]
Je pense que la question se pose uniquement pour les identifiants de ROROrganization. 
Dans ce contexte nous avons slicé les identifiants par la valeurs de leur type, qui est discriminant pour leur identification. 

Pour les recherches sur les identifiants qui est de type token la recherche  (cf. http://hl7.org/fhir/search.html#token) peut s'écrire [parameter]=[system]|[code]
-> Meme si le système est précisé dans notre cas cela ne sera pas suffisant pour pointer un identifiant en particulier car le système n'est pas discriminant.  Cf #83 pour la réflexion sur les systèmes des identifiants. 

Pour chercher par type et non par système, il est précisé dans la spécification qu'il est possible d'utiliser le modificateurs of-type (http://hl7.org/fhir/search.html#modifieroftype).
Ce modificateur existe bien en R4. 
La syntaxe est alors : [system]|[code]|[value] avec le système et le code qui se réfère au type. 

L'utilisation de ce modificateur à valider. 
Si c'est le cas nous devrons l'ajouter dans la spécification.

**Comment by paulineheurtebise** [comment]
Si la décision est prise d'ajouter ce modificateur, les impacts sont : 
- Ajouter dans la spécification 
- Ajouter ou modifier les scénarios exemples

**Comment by sdemeyANS** [comment]
@jcserafini ok pour toi?

**Comment by paulineheurtebise** [comment]
Atelier 06/09 :

- Le modificateur n’est pas encore développé. 
- Ciblé sur la release R3.1 ( ou 3.0 ?) Doit être présent dans l’IG (à minima la preview) courant octobre pour ATOS.

**Comment by paulineheurtebise** [comment]
Hello, 
J'ai ajouté le modificateur uniquement dans le narratif. 
A voir si par la suite il sera nécessaire de changer les scénarios.
